### ISSUE TITLE
How to lock down access?

### ISSUE THREAD

**Issue by Ramblurr** [kubernetes-sigs/nfs-subdir-external-provisioner#10]
Is it possible to lockdown access so only the privileged nfs container (the  provisioner?) can mount and access the NFS share directly?

I don't want other containers to be able to mount the share themselves.

Perhaps this is possible with a NetworkPolicy?

Would love to see an example of this in the readme.

**Comment by b-slim** [comment]
@Ramblurr please help me understand, how the containers can mount the NFS share ? is that because it is running as root ?

**Comment by kmova** [comment]
@Ramblurr - the provisioner just helps to create a NFS PV and doesn't mount the NFS share itself. The contain that needs to access the share needs to create a PVC. 

If you like to restrict some of the containers from using the NFS PV, is writing a OPA policy or admission webhook an option?

**Comment by Ramblurr** [comment]
Thanks for the replies @kmova  and @b-slim, I haven't forgotten about this, but need to get some time for testing.
