### ISSUE TITLE
nfs-client-provisioner Pod are getting failed

### ISSUE THREAD

**Issue by darpan91** [kubernetes-sigs/nfs-subdir-external-provisioner#102]
We have install & confgured NFS server and created a storage class for NFS dynamic storage provisioning in Openshift. 
We have followed the steps mentioned in the below IBM technote for NFS client provisioning:
https://www.ibm.com/support/pages/node/6356629
NFS is installed on barematel outside of ibm cloud.
managed-nfs-storage created successfully. nfs-client-provisioner Pod are getting failed with below error. 

error message : 

Unable to attach or mount volumes: unmounted volumes=[nfs-client-root], 
unattached volumes=[nfs-client-provisioner-token-262w4 nfs-client-root]: timed out waiting for the condition
PodPnfs-client-provisioner-5768756468-p7mqzNamespaceNScp4a-baw

MountVolume.SetUp failed for volume "nfs-client-root" : mount failed: exit status 32 Mounting command: 
systemd-run Mounting arguments: --description=Kubernetes transient mount for 
/var/data/kubelet/pods/daa62ce4-b8db-4c61-b3cc-a9a7fadec56b/volumes/kubernetes.io~nfs/nfs-client-root --scope -- 
mount -t nfs 10.254.X.X:/nfs-share/cp4auto-storage/ /var/data/kubelet/pods/daa62ce4-b8db-4c61-b3cc-a9a7fadec56b/volumes/kubernetes.io~nfs/nfs-client-root Output:
 Running scope as unit run-68677.scope. mount.nfs: Connection timed out 

Regards,
Darpan Yadav

**Comment by nikos445** [comment]
any luck? i have same issue

**Comment by yonatankahana** [comment]
hi @darpan91, can you show us `kubectl describe all -Al app=nfs-subdir-external-provisioner` output?
plus, can you make sure that you can manually mount the exported folder on the host machine?

**Comment by colearendt** [comment]
@darpan91 "Connection timed out" is usually a networking issue - you should be sure that your kubernetes nodes have access to your NFS server.

**Comment by Bo-Zi** [comment]
> @darpan91 
> 
> **EDIT:** I ran into an error message like:
> ...
> Output: mount.nfs: Protocol not supported
> 
> The solution was changing the `v4.2` mount option to `v4`

Yes, you should be careful with NFS-server version and parameters.
Running:
`rpcinfo <NFS.server.addr>` from any host in the LAN, or
`rpcinfo` directly at the NFS-server, and
`mount <NFS.server.addr>:</nfs/exports/dir> /tmp/nfstest -v` with "-v" parameter from any node,
 might be very helpful while debugging.

Here is an extended solution to overcome NFS protocol incompatibility:
https://github.com/kubernetes/kubernetes/issues/24249#issuecomment-452551097

**Comment by justas147** [comment]
Can the timeout be cause by something other then networking? I'm also getting the `dial tcp 10.0.0.1:443: i/o timeout` error randomly, however k8s nodes can access the nfs server, they are in the same network and besides these restarts the provisioner works fine.
