### ISSUE TITLE
Support for ARM64 architecture 

### ISSUE THREAD

**Issue by codayblue** [kubernetes-sigs/nfs-subdir-external-provisioner#11]
I see there is support for ARM v7 from the make file. I am attempting currently to get this working on my Rock64 Armbian k3s cluster. I can help test and work on the pipeline I just need to be pointed in a direction. Currently thinking about trying to build and deploy to from a fork to another quay repo just to have something working.

Thank you,
Cody Moss

**Comment by fourstepper** [comment]
![image](https://user-images.githubusercontent.com/49439044/98483064-e2316180-2205-11eb-9ea9-5a695a1299d8.png)
Raspberry Pi 4 - 4GB on Ubuntu 20.04 ARM64

**Comment by yonatankahana** [comment]
we do support arm64 and this issue is just old. 
@codayblue if you still have trouble with the latest release and arm64 please open new issue.

/close
