### ISSUE TITLE
Failure to install with nfs mount options

### ISSUE THREAD

**Issue by JDSQ** [kubernetes-sigs/nfs-subdir-external-provisioner#112]
I issued this command:
```
helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=<server-hostname> \
    --set nfs.path=/scratch \
    --set nfs.mountOptions='nfsvers=4.1,rsize=1048576,wsize=1048576,hard=,timeo=600,retrans=2,noresvport='

```
And received this error:
`Error: template: nfs-subdir-external-provisioner/templates/storageclass.yaml:28:19: executing "nfs-subdir-external-provisioner/templates/storageclass.yaml" at <.Values.nfs.mountOptions>: range can't iterate over nfsvers=4.1`

What should I be doing?

**Comment by yonatankahana** [comment]
`nfs.mountOptions` is a list, which means you need to use the `{}` symbols (as described in [The Format and Limitations of --set](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set)):

```bash
helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=<server-hostname> \
    --set nfs.path=/scratch \
    --set "nfs.mountOptions={nfsvers=4.1,rsize=1048576,wsize=1048576,hard=,timeo=600,retrans=2,noresvport=}"
```

**Comment by mattrpav** [comment]
FYI-- I ran into this, and putting the quotes around the value works for me.

`    --set nfs.mountOptions="{rw,sync,vers=4.2,proto=tcp,soft,retrans=3,timeo=100}" \
`

kubectl get sc..

`
...
mountOptions:
- rw
- sync
- vers=4.2
- proto=tcp
- soft
- retrans=3
- timeo=100

...
`
