### ISSUE TITLE
Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.

### ISSUE THREAD

**Issue by whaleBoot** [kubernetes-sigs/nfs-subdir-external-provisioner#115]
Hi, I am try to resize my pvc, but pvc size not change. 

 Warning : Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.

thx.

**Comment by whaleBoot** [comment]
[issues](https://github.com/kubernetes-retired/external-storage/issues/1235
)

@wongma7 : the nfs-client-provisioner is not capable of expanding volumes. In fact, it does not enforce the size of volumes at all, so a PV that says 1Gi may in fact have contain/write more than 1Gi of data in its path. AFAIK, there is no standard quota/limit mechanism for NFS. Apologies if this is not clear.

**Comment by whaleBoot** [comment]
This means that as long as my NFS server has enough space, my application is not limited by the size of the PVC ?

**Comment by yonatankahana** [comment]
> This means that as long as my NFS server has enough space, my application is not limited by the size of the PVC ?

yes, the pvc size is not enforced. no expansion required.

**Comment by whaleBoot** [comment]
> > This means that as long as my NFS server has enough space, my application is not limited by the size of the PVC ?
> 
> yes, the pvc size is not enforced. no expansion required.

thanks

**Comment by nareshpandianpc** [comment]
what was the solution for  that ?

**Comment by rg2609** [comment]
@whaleBoot and @yonatankahana, what was the sol. to resolve this issue?

**Comment by whaleBoot** [comment]
> https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/115#issuecomment-867459750

**Comment by whaleBoot** [comment]
> @whaleBoot and @yonatankahana, what was the sol. to resolve this issue?

https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/115#issuecomment-867459750
