### ISSUE TITLE
Pod won't start if nfs-commons are not available on cluster nodes

### ISSUE THREAD

**Issue by abrakhim** [kubernetes-sigs/nfs-subdir-external-provisioner#120]
Hello, 

i installed nfs-subdir-external-provisioner via helm3 on a 3-node-microk8s-Cluster. The Provisioner pod failed to start with this message in Events:

```microk8s.kubectl describe pod nfs-subdir-external-provisioner-XXXXXXXXXXXXXX

Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Warning  FailedMount  32s (x8 over 96s)  kubelet            MountVolume.SetUp failed for volume "nfs-subdir-external-provisioner-root" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs XXXXXXXXXXX /var/snap/microk8s/common/var/lib/kubelet/pods/XXXXXXXXXXXXXXXXXXXXXXXXXXXX/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root
Output: mount: /var/snap/microk8s/common/var/lib/kubelet/pods/XXXXXXXXXXXXXXXXXXXXXXXXXX/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

This was fixed by installing nfs-commons package on all nodes, but it should be mentioned as a prereq in the install notes.

**Comment by timothyclin** [comment]
replicated the issue on my micro3ks cluster running 64bit ubuntu on RaspberryPi 4b 

kubectl describes of the nfs-subdir-external-provisioner pod 

Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    117s                default-scheduler  Successfully assigned default/nfs-subdir-external-provisioner-5c478b456c-4s7nr to odin
  Warning  FailedMount  53s (x8 over 117s)  kubelet            MountVolume.SetUp failed for volume "nfs-subdir-external-provisioner-root" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs x.x.x.x:/mnt/k8s-nfs/ /var/lib/kubelet/pods/1b48c746-f5ed-46b9-a7dc-a08f170d5df5/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root
Output: mount: /var/lib/kubelet/pods/1b48c746-f5ed-46b9-a7dc-a08f170d5df5/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

**Comment by dreske** [comment]
installing nfs-common on the node solves the problem for me
