### ISSUE TITLE
PVs not created on EFS

### ISSUE THREAD

**Issue by alessio4tech** [kubernetes-sigs/nfs-subdir-external-provisioner#122]
version: v4.0.2
installation method: manual (no Helm chart)
K8s version: EKS 1.19

Issue:

the NFS provisioner claims to have created a volume in EFS:

I0707 16:38:11.043204       1 controller.go:1317] provision "default/test-claim" class "managed-nfs-storage": started
I0707 16:38:11.054723       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-claim", UID:"bb4bd2b1-2237-4209-9894-b6ac135ace4c", APIVersion:"v1", ResourceVersion:"458642", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-claim"
I0707 16:38:11.054826       1 controller.go:1420] provision "default/test-claim" class "managed-nfs-storage": volume "pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c" provisioned
I0707 16:38:11.054846       1 controller.go:1437] provision "default/test-claim" class "managed-nfs-storage": succeeded
I0707 16:38:11.054850       1 volume_store.go:212] Trying to save persistentvolume "pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c"
I0707 16:38:11.337955       1 volume_store.go:219] persistentvolume "pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c" saved
I0707 16:38:11.338053       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-claim", UID:"bb4bd2b1-2237-4209-9894-b6ac135ace4c", APIVersion:"v1", ResourceVersion:"458642", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume **pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c**

however, the PV does not exist on the EFS file system and the pods cannot start because the volume is not found - kubelet logs:

Jul  7 16:42:25 ip-192-168-4-52 kubelet: I0707 16:42:25.397041    5268 reconciler.go:269] operationExecutor.MountVolume started for volume "pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c" (UniqueName: "kubernetes.io/nfs/8632c33d-37f7-464b-84ce-3796a13f862f-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c") pod "test-pod" (UID: "8632c33d-37f7-464b-84ce-3796a13f862f")
Jul  7 16:42:25 ip-192-168-4-52 systemd: Started Kubernetes transient mount for /var/lib/kubelet/pods/8632c33d-37f7-464b-84ce-3796a13f862f/volumes/kubernetes.io~nfs/pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c.
Jul  7 16:42:25 ip-192-168-4-52 kubelet: E0707 16:42:25.439612    5268 mount_linux.go:150] Mount failed: exit status 32
Jul  7 16:42:25 ip-192-168-4-52 kubelet: Mounting command: systemd-run
Jul  7 16:42:25 ip-192-168-4-52 kubelet: Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/8632c33d-37f7-464b-84ce-3796a13f862f/volumes/kubernetes.io~nfs/pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c --scope -- mount -t nfs -o hard,noresvport,retrans=2,rsize=1048576,timeo=600,vers=4.1,wsize=1048576 xxxx.efs.eu-west-1.amazonaws.com:/pvc/default-test-claim-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c /var/lib/kubelet/pods/8632c33d-37f7-464b-84ce-3796a13f862f/volumes/kubernetes.io~nfs/pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c
Jul  7 16:42:25 ip-192-168-4-52 kubelet: Output: Running scope as unit run-8385.scope.
Jul  7 16:42:25 ip-192-168-4-52 kubelet: mount.nfs: mounting xxxx.efs.eu-west-1.amazonaws.com:/pvc/default-test-claim-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c failed, reason given by server: No such file or directory
Jul  7 16:42:25 ip-192-168-4-52 kubelet: E0707 16:42:25.440852    5268 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/nfs/8632c33d-37f7-464b-84ce-3796a13f862f-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c podName:8632c33d-37f7-464b-84ce-3796a13f862f nodeName:}" failed. No retries permitted until 2021-07-07 16:44:27.440818649 +0000 UTC m=+4259.482223844 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c\" (UniqueName: \"kubernetes.io/nfs/8632c33d-37f7-464b-84ce-3796a13f862f-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c\") pod \"test-pod\" (UID: \"8632c33d-37f7-464b-84ce-3796a13f862f\") : mount failed: exit status 32\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/8632c33d-37f7-464b-84ce-3796a13f862f/volumes/kubernetes.io~nfs/pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c --scope -- mount -t nfs -o hard,noresvport,retrans=2,rsize=1048576,timeo=600,vers=4.1,wsize=1048576 xxxxxx.efs.eu-west-1.amazonaws.com:/pvc/default-test-claim-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c /var/lib/kubelet/pods/8632c33d-37f7-464b-84ce-3796a13f862f/volumes/kubernetes.io~nfs/pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c\nOutput: Running scope as unit run-8385.scope.\nmount.nfs: mounting xxxxxx.efs.eu-west-1.amazonaws.com:/pvc/default-test-claim-pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c failed, reason given by server: No such file or directory\n"

The PV/PVC are bound:

$ kubectl  -n default get pvc
NAME         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
test-claim   Bound    pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c   1Mi        RWX            managed-nfs-storage   20m

$ kubectl  -n default get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 
   pvc-bb4bd2b1-2237-4209-9894-b6ac135ace4c   1Mi        RWX            Delete           Bound    default/test-claim                                             managed-nfs-storage            6m46s

I can mount EFS on the EKS node successfully, but the dynamic provisioning of an EFS volume does not appear to work. Any hints would be much appreciated.

**Comment by notbucai** [comment]
hello, Did you solve your problem? I have the same problem.
