### ISSUE TITLE
Delete and/or Archive does not work with nested directory in pathPattern value

### ISSUE THREAD

**Issue by unreal-altran** [kubernetes-sigs/nfs-subdir-external-provisioner#127]
Hi, 

nfs-subdir-external-provisioner works well with all plain combination of pathPattern value,
but in cases of nested directory ​​its deletion / archiving fails  (creation of the folder continues to work well) 

Example...
**NOT WORK**

> pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"

**WORK**

> pathPattern: "${.PVC.namespace}-${.PVC.annotations.nfs.io/storage-path}"

Error in nfs-subdir-external-provisioner pods is:

> W0723 17:19:54.605380       1 provisioner.go:146] path /persistentvolumes/test-claim does not exist, deletion skipped

**Comment by fuerer** [comment]
the basePath could be the problem:
```
func (p *nfsProvisioner) Delete(ctx context.Context, volume *v1.PersistentVolume) error {
	path := volume.Spec.PersistentVolumeSource.NFS.Path  # /nfsshare/subdirectory/pvname
	basePath := filepath.Base(path)   # pvname
	oldPath := filepath.Join(mountPath, basePath) # /persistentvolumes/pvname

	if _, err := os.Stat(oldPath); os.IsNotExist(err) {
		glog.Warningf("path %s does not exist, deletion skipped", oldPath)
		return nil
	}
```

If I am not wrong, the directories in between are lost like that, maybe something like this would work (not sure though I am not a developer):
 `  basePath := strings.SplitN(path, "/", 3)  # when path is something like /nfsshare/subdir/pv
`

**Comment by Opulski** [comment]
Could be solved by replacing the nfsProvisioner.path in the PV Path by the mountpath like this:

```
func (p *nfsProvisioner) Delete(ctx context.Context, volume *v1.PersistentVolume) error {
	path := volume.Spec.PersistentVolumeSource.NFS.Path  # /nfsshare/subdirectory/pvname
	//basePath := filepath.Base(path)   # pvname
        //instead use Replace() on path since nfsProvisioner.path is mounted on mountPath
        basePath := strings.Replace(path, p.path, mountPath, 1)
	oldPath := filepath.Join(mountPath, basePath) # /persistentvolumes/pvname

	if _, err := os.Stat(oldPath); os.IsNotExist(err) {
		glog.Warningf("path %s does not exist, deletion skipped", oldPath)
		return nil
	}
```
