### ISSUE TITLE
Helm: ReclaimPolicy for the nfs-subdir-external-provisioner pv is set to the same as the generated StorageClass.

### ISSUE THREAD

**Issue by olifly** [kubernetes-sigs/nfs-subdir-external-provisioner#128]
Hi.

The `persistentVolumeReclaimPolicy` for the nfs-subdir-external-provisioner PersistentVolume is set to the same value as the  `reclaimPolicy` for the generated StorageClass (`.Values.storageClass.reclaimPolicy`in values.yaml).

Our storage setup, especially some older kubernetes cluster we have, is so that we would like to have these as different values (storageClass = Delete and PV = Retain). 

The nfs-subdir-external-provisioner pv is connecting to a NFS volume that has other data than the provisioned volumes by nfs-subdir-external-provisioner so having the ReclaimPolicy = Delete is not something we would like to have :)

**Comment by QuingKhaos** [comment]
Same problem here. The root PV for the provisioner should be retained, while the default reclaimPolicy for the dynamic PVs created by the provisioner should be Delete.

**Comment by olifly** [comment]
I can implement this feature and make a pull request if the maintainers of this repository want :)

**Comment by yonatankahana** [comment]
> I can implement this feature and make a pull request if the maintainers of this repository want :)

we will :)
contribution is always appreciated :+1:
