### ISSUE TITLE
Avoid crashing when API is not reachable

### ISSUE THREAD

**Issue by johanfleury** [kubernetes-sigs/nfs-subdir-external-provisioner#13]
I’m running a kubernetes cluster with a single controller node and from time to time this controller node (e.g. during upgrades or reboots) might not be reachable.

Currently, when that happen, the provisioner “crashes” (exit with a non 0 status) and its pod goes into a crash loop as Kubernetes tries to restart it.

It would be great if the provisioner could handle this error in some way and not exit immediately (maybe retry for a certain time before exiting).

**Comment by kmova** [comment]
@johanfleury, a similar issue has been fixed in the nfs-external-storage-provisioner via this PR https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/11

Would you like to contribute the same change to this repository?

**Comment by johanfleury** [comment]
I can work on that. Do you think disabling leader election is the best way to solve that?

**Comment by rombert** [comment]
Is this fixed by #22 ?

**Comment by johanfleury** [comment]
I mean, if I disable leader election, most probably. But that feels like a bad idea for “HA” deployment, for rollouts, etc.
