### ISSUE TITLE
volumeexpansion doesn't work.

### ISSUE THREAD

**Issue by stevensea-r** [kubernetes-sigs/nfs-subdir-external-provisioner#135]
Hi,
I installed the NFS storage class on Rancher. But when I try to update my deployment with more space on PVC with volumeExpansion. The PVC capacity is still shown (1Gi) no change. But when I open and check the PVC YAML file. I see the requests: storage: change to 2Gi already.
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs

Please help me with this issue.
Thanks.

**Comment by yonatankahana** [comment]
please note the footer of the readme for the new section `NFS provisioner limitations/pitfalls`

> Storage resize/expansion operations are not presently supported in any form. You will end up in an error state: `Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.`

they cannot be expanded and anyway, their size not enforced:

> The provisioned storage limit is not enforced. The application can expand to use all the available storage regardless of the provisioned size.
