### ISSUE TITLE
NFS Credentials

### ISSUE THREAD

**Issue by noyessie** [kubernetes-sigs/nfs-subdir-external-provisioner#136]
Hi

My NFS server needs credentials ( for security reason ). Is there a way to specify the NFS credentials ?

Thanks.

**Comment by kmova** [comment]
This is currently not supported @noyessie @shengzhou1216. This provisioner depends on the kubernetes in-tree "nfs" volume. This feature could be better implemented on the new NFS CSI driver. 

cc: @msau42

**Comment by GuyPaddock** [comment]
This will become a lot more important with solutions that use NFS 4.1 with authentication (e.g. Qumulo).

**Comment by denismoc** [comment]
Commenting my support for getting authentication/credentials incorporated into this. I believe this will greatly improve the project.
