### ISSUE TITLE
Unable to supply `nodeSelector` on command line

### ISSUE THREAD

**Issue by crd477** [kubernetes-sigs/nfs-subdir-external-provisioner#14]
Presumably I'm doing something wrong but I tried to supply a value for `nodeSelector` in the following manner:
```
helm install foo stable/nfs-client-provisioner --set nodeSelector='{"node-role.kubernetes.io/master": ""}' ...
```
which results in the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.nodeSelector): invalid type for io.k8s.api.core.v1.PodSpec.nodeSelector: got "array", expected "map"
```

Could you please provide a concrete example of the correct way to do this?

I was able to work around the problem by doing `helm pull`, editing `values.yaml` and then installing the chart from the local directory.

**Comment by yonatankahana** [comment]
wrong cli usage, this should work:
```console
helm install foo stable/nfs-client-provisioner --set nodeSelector."node-role\\.kubernetes\\.io/master"=
```
