### ISSUE TITLE
not possible to use pvname in pathpattern

### ISSUE THREAD

**Issue by robkooper** [kubernetes-sigs/nfs-subdir-external-provisioner#149]
Looking at the default pattern it uses `${.PVC.namespace}-${.PVC.name}-${pvname}`. it is possible to get both the namespace and the name of the PVC, but not the name of the PV. Is it possible to make this a variable that can be accessed.

I noticed that the variables are set in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/cmd/nfs-subdir-external-provisioner/provisioner.go#L92.

**Comment by QuingKhaos** [comment]
@robkooper What's your need for the PV name in the path pattern?

**Comment by robkooper** [comment]
I have a PR ready, and a signed cla by the University.  Should be able to submit something soon.

**Comment by robkooper** [comment]
My need is to be able to :

1. recreate the same pattern that is used by the provider
2. make sure that my name is unique across different installations of the PVC

For example in my case I'd like to use `{.PVC.namespace}/{.PVC.name}/{.PVC.volume}` as the unique name for the folder where the files will be stored.

Looking at the code it is a simple fix, I have something that should work, waiting for the CLA to be accepted and I'll create the PR.
