### ISSUE TITLE
No Releases, No Artifacts, No Helm Chart Support, No updated CHANGELOG

### ISSUE THREAD

**Issue by darkn3rd** [kubernetes-sigs/nfs-subdir-external-provisioner#15]
* There are no tags or releases for this project.  
* The CHANGELOG is stale with last update for v2.0.1 on Aug 8, 2017.  There are no corresponding tags, sha code, etc.
* Original archived release had release of `nfs-client-provisioner-v3.1.0-k8s1.11`
* Official Docker Image quay.io/external_storage/nfs-client-provisioner has a release from 2 years ago for `v3.1.0-k8s1.11`
* Official Helm Chart Maintained soon to be archived repo: https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner

**Comment by kmova** [comment]
@darkn3rd - thanks for your interest in this project and for summarizing the pending tasks that have to be completed. I will use this issue to update the progress over the next few days! Also, feel free to contribute to any of the pending tasks.

**Comment by rkevin-arch** [comment]
We're currently using the `nfs-client-provisioner` helm chart, and there doesn't seem to be an official replacement yet. With the stable repo about to be deleted in less than 2 weeks, is there anything we can do to help speed this up?

**Comment by rombert** [comment]
@kmova - are there any plans to provide a new Helm chart? I'd like to add support for disabling leader election (#22) but I'm not sure where to submit the changes.

**Comment by llech** [comment]
Is there any docker image built since the branching from the nfs-client-provisioner? Are there any relevant changes made since?
The nfs-client-provisioner:latest was working fine in Kubernetes 1.19.

**Comment by rombert** [comment]
@llech - I am interested in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/22

**Comment by kmova** [comment]
Almost there. Just trying to get the process right for the automated builds via these PRs:
- https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/30
- https://github.com/kubernetes/test-infra/pull/20233

As soon as the above two are merged, will work on enabling these automated builds for this repo.

**Comment by yonatankahana** [comment]
@kmova I will love to help with bringing the helm chart to this repository and maintain it. let me know if my help is needed.

**Comment by kmova** [comment]
@yonatankahana - that would be awesome! please go ahead.

**Comment by davidkarlsen** [comment]
> Almost there. Just trying to get the process right for the automated builds via these PRs:
> 
> * [kubernetes-sigs/nfs-ganesha-server-and-external-provisioner#30](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/pull/30)
> * [kubernetes/test-infra#20233](https://github.com/kubernetes/test-infra/pull/20233)
> 
> As soon as the above two are merged, will work on enabling these automated builds for this repo.

Those two are merged now.

**Comment by kmova** [comment]
And one more to go: https://github.com/kubernetes/org/issues/2389

Also started working on #29 for automating builds on this repo.

**Comment by pierluigilenoci** [comment]
Is there any news regarding a new chart on the Hub?

**Comment by yonatankahana** [comment]
> Is there any news regarding a new chart on the Hub?

I am waiting for #30 to be merged so we can continue to work on automation and uploading to repository.

**Comment by immanuelfodor** [comment]
@kmova has just received the missing permissions today, the project will definitely progress :)

**Comment by yonatankahana** [comment]
another progress made.
* the helm chart merged (#30)
* tag `4.0.0-rc1` created

seems we are very close to the first image and chart release.

**Comment by kmova** [comment]
Another step to cross. https://github.com/kubernetes/test-infra/pull/20432

**Comment by alexdresko** [comment]
> Another step to cross. [kubernetes/test-infra#20432](https://github.com/kubernetes/test-infra/pull/20432)

Merged 7 hours ago. 👍
