### ISSUE TITLE
nfs-subdir-external-provisioner does not deploy on microk8s

### ISSUE THREAD

**Issue by pauloalima** [kubernetes-sigs/nfs-subdir-external-provisioner#150]
I tried deploying with helm3, using the yaml files and also rebuild on my local machine but all these attempts failed the same way.

The pod Neve comes up, I noted the following errors:
kubectl describe pod nfs-client-provisioner-6ddd8b7dc4-mwcwp
Name:         nfs-client-provisioner-6ddd8b7dc4-mwcwp
Namespace:    default
Priority:     0
Node:         tranbics-hub/192.168.102.221
Start Time:   Wed, 29 Sep 2021 10:39:00 -0400
Labels:       app=nfs-client-provisioner
              pod-template-hash=6ddd8b7dc4
Annotations:  cni.projectcalico.org/podIP: 10.1.101.210/32
              cni.projectcalico.org/podIPs: 10.1.101.210/32
Status:       Pending
IP:           10.1.101.210
IPs:
  IP:           10.1.101.210
Controlled By:  ReplicaSet/nfs-client-provisioner-6ddd8b7dc4
Containers:
  nfs-client-provisioner:
    Container ID:   
    Image:          k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Environment:
      PROVISIONER_NAME:  tranbics-hub/nfs
      NFS_SERVER:        192.168.102.221
      NFS_PATH:          /srv/nfs/kubedata
    Mounts:
      /persistentvolumes from nfs-client-root (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9rcrg (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nfs-client-root:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.102.221
    Path:      /srv/nfs/kubedata
    ReadOnly:  false
  kube-api-access-9rcrg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  2m43s               default-scheduler  Successfully assigned default/nfs-client-provisioner-6ddd8b7dc4-mwcwp to tranbics-hub
  Warning  Failed     42s                 kubelet            Error: context deadline exceeded
  Normal   Pulled     1s (x5 over 2m42s)  kubelet            Container image "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2" already present on machine
  Warning  Failed     1s (x4 over 41s)    kubelet            Error: failed to reserve container name "nfs-client-provisioner_nfs-client-provisioner-6ddd8b7dc4-mwcwp_default_06bfd9db-50c6-4281-95f7-b13b8f83a2bd_0": name "nfs-client-provisioner_nfs-client-provisioner-6ddd8b7dc4-mwcwp_default_06bfd9db-50c6-4281-95f7-b13b8f83a2bd_0" is reserved for "d3e3237a9cac2e59f57c600b41f017d84b200f66a8e98d0b3fff47eb7aa8ba5c"

Any clues on what could be going wrong for me?

**Comment by PhotoTeeborChoka** [comment]
The deployment on microk8s works in our case.
