### ISSUE TITLE
Integrating multiple NFS Server

### ISSUE THREAD

**Issue by MeranaTona** [kubernetes-sigs/nfs-subdir-external-provisioner#153]
Hi all,

im new to this topic and not sure if my understanding is corrent. In K8s I would like dynamically provide access to storage of two NFS servers. Those two severs are not part of the K8s cluster. Each server is running on its own host. 

Following your documentation, in K8s, I would start a NFS privisioner for each NFS Server by running this command:
```
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=x.x.x.x \
    --set nfs.path=/exported/path
```

So eventually, I would end up with 2 NFS Servers and in K8s with 2 NFS provisioners. Could you please tell me if this is correct and considered best practice? Following your examples, could I still use a single "managed-nfs-storage" storage class (step 7)? Or would it complicate the process of creating PVCs etc, because I have to distinguish between multiple provisioners/storage classes etc.?

Thank you in advance,

Greetings

**Comment by yonatankahana** [comment]
just for the record, the solution is documented now in the chart readme, #166
