### ISSUE TITLE
Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s"

### ISSUE THREAD

**Issue by ilmal** [kubernetes-sigs/nfs-subdir-external-provisioner#160]
Heyo,

I've been using this for a while now without any problems, but all of a sudden my pod kept on crashing and spitting out the err message: 

`F1121 17:35:15.868874       1 provisioner.go:247] Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
`

What should I do to fix this?

Thanks

**Comment by ilmal** [comment]
The problem seemed to be from my networking pods not configured correctly. And so not from nfs.

**Comment by agelosnm** [comment]
> 

How exactly did you resolve the pods networking issues?

**Comment by yonatankahana** [comment]
> @ilmal How exactly did you resolve the pods networking issues?

if you don't have CNI (e.g calico, flannel) installed then you should install one.

if you have CNI installed and it's not working, you should troubleshoot the problem depends on what CNI you have installed.

**Comment by agelosnm** [comment]
> > @ilmal How exactly did you resolve the pods networking issues?
> 
> if you don't have pod networking (e.g calico, flannel) installed then you should install one.
> 
> if you have pod networking installed and it's not working, you should troubleshoot the problem depends on what you have installed. for example if you use calico you can read its pods logs (calico-node-*).
> 
> read more: https://kubernetes.io/docs/concepts/cluster-administration/networking/

@yonatankahana I'm using weave net as my pod networking solution. You think that this may be the issue? I will test with calico & flannel as well. Thanks anyway! 🥇

**Comment by ilmal** [comment]
Hi! 
Sorry for late reply. 

The problem I had was with flannel networking and not with nfs at all. I later found out that none of my pods had internet access. And so, that is why I got this error. 

It was a while ago, but if I remember correctly the problem I had was with taints and tolerations. I was messing around with these and put taints on a majority of the nodes. That lead to my networking pods not starting up on all the nodes, which resulted in my pods not having access to the internet. (The networking applications need to run a pod on every single node in order to work properly)

So, my solution was to simply allow my networking pods to run on every node.

**Comment by agelosnm** [comment]
> 

Hi!

No worries for the reply!

@yonatankahana comment "unblocked" me as I figured that the issue was related with the weave net. I installed calico in my cluster, and everything is working smoothly up until now!

Thank you both guys for your help!
