### ISSUE TITLE
RKE2 [FailedCreate] pods "nfs-client-provisioner-57cc4b4c94-" is forbidden: PodSecurityPolicy: unable to admit pod: [] 

### ISSUE THREAD

**Issue by aintbrokedontfix** [kubernetes-sigs/nfs-subdir-external-provisioner#161]
I get the following error when trying to deploy the provisioner on RKE2. The RKE2 deployment is configured as "permissive/unrestricted". However, the provisioner does not start. 

pods "nfs-client-provisioner-57cc4b4c94-" is forbidden: PodSecurityPolicy: unable to admit pod: []:Deployment does not have minimum availability.

**Comment by umberto10** [comment]
any update on this?
