### ISSUE TITLE
Helm does not support archiveOnDelete when setting pathPattern

### ISSUE THREAD

**Issue by possani** [kubernetes-sigs/nfs-subdir-external-provisioner#167]
Hello everyone,

This issue was already described [here](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/91), but I could not reopen it.

Additional information about it:

Error:
```
I0104 11:33:32.877762       1 controller.go:1450] delete "pvc-4f5bc7e2-7d77-4836-92e6-61177b9ab561": started
W0104 11:33:32.882279       1 provisioner.go:146] path /persistentvolumes/test-nfs does not exist, deletion skipped
```

This happens because [fullPath](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/eae7143d98f8613c1f29a82154e06063924f2e08/cmd/nfs-subdir-external-provisioner/provisioner.go#L109) includes the _pathPattern_ when set, but when archiving it, it only uses the [mountPath](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/eae7143d98f8613c1f29a82154e06063924f2e08/cmd/nfs-subdir-external-provisioner/provisioner.go#L184).

**Comment by hillbun** [comment]
@possani  @humblec 

is this issue solved with new release?

**Comment by possani** [comment]
> @possani @humblec
> 
> is this issue solved with new release?

Hi @hillbun, I haven't tried the new release yet, but I'm watching [this PR](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/221).

**Comment by rmoreas** [comment]
unfortunately it's still not merged. Who can give this a push?

**Comment by hillbun** [comment]
@rmoreas   is fix is not released yet?

**Comment by rmoreas** [comment]
[The change](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/221/files) is not yet [in the master branch](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/cmd/nfs-subdir-external-provisioner/provisioner.go#L149), so I suppose not.

**Comment by hillbun** [comment]
may you help me to look at this issue?

https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/231
