### ISSUE TITLE
Add option to set volumeBindingMode

### ISSUE THREAD

**Issue by robertengelmann** [kubernetes-sigs/nfs-subdir-external-provisioner#172]
Here is an idea for contributors to this project:
It would be nice to set the [volumeBindingMode](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) option on the storage class in the helm chart. For some deployments (e.g. [ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-storage-recommendations.html#k8s_storage_class_settings)) it is desireable to adjust this value. 
An additional line in  `nfs-subdir-external-provisioner/charts/nfs-subdir-external-provisioner/templates/storageclass.yaml` and  `nfs-subdir-external-provisioner/charts/nfs-subdir-external-provisioner/values.yaml` should do the trick, but I can't create a pull request myself, for reasons.

Thank you and have a nice day.

**Comment by tinguin** [comment]
Think i can help out here. But first i try out and verify it works and check out the Contributor Guide and CLA.

/remove-lifecycle rotten
