### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by jurschel** [kubernetes-sigs/nfs-subdir-external-provisioner#174]
It appears that any image after 4.0.2 is missing?  Have they moved or have I made an error?  This was working a week or so ago as I deployed 4.0.14 just fine now I went to redeploy it this morning and find that they are all gone back to 4.0.2...

**Comment by jurschel** [comment]
`podman pull --all-tags k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
Trying to pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.0...
Getting image source signatures
Copying blob 9e4425256ce4 done
Copying blob 3edf8ea6fb70 done
Copying config 3beaacba3f done
Writing manifest to image destination
Storing signatures
Trying to pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.1...
Getting image source signatures
Copying blob 9e4425256ce4 skipped: already exists
Copying blob f32b919eb4ab done
Copying config 686d373128 done
Writing manifest to image destination
Storing signatures
Trying to pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2...
Getting image source signatures
Copying blob 528677575c0b skipped: already exists
Copying blob 60775238382e skipped: already exists
Copying config 932b0bface done
Writing manifest to image destination
Storing signatures
3beaacba3ff4821eabd4e15b7fbe99c95e079f74d3bf60ef2ba2fefda5d47b42
686d3731280a72025a09c057d89f208d39d757be89c9291075a36f91a5abd550
932b0bface75b80e713245d7c2ce8c44b7e127c075bd2d27281a16677c8efef3'

**Comment by yonatankahana** [comment]
hi @jurschel
the latest version of the provisioner is [4.0.2](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/tag/v4.0.2), you may be confused with the helm chart version which is currently [4.0.15](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/tag/nfs-subdir-external-provisioner-4.0.15).

**Comment by jurschel** [comment]
Sorry for the mistake.

**Comment by WuQic** [comment]
use eipwork/nfs-subdir-external-provisioner
