### ISSUE TITLE
ROX(readonlymany) does not work

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubernetes-sigs/nfs-subdir-external-provisioner#18]
I created a PVC with access modes = ROX and mounted this PVC to a pod, I found I can write data to this volume, so it's not read-only.

I'm using nfs-client-provisioner:v3.1.0-k8s1.11.

- Is it possible to support ROX?
- If ROX is not supported, can nfs-client-provisioner reject/fail the PVC request with ROX?

Test info for reference:
```
root@i-os8hfxab:~/stone
$ kubectl get pvc nfs-rom -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"nfs-rom","namespace":"default"},"spec":{"accessModes":["ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"nfs-client"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-provisioner
  creationTimestamp: "2020-11-09T01:35:11Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: nfs-rom
  namespace: default
  resourceVersion: "27851685"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/nfs-rom
  uid: 3e774225-3088-4390-849c-7f621ecb8ae0
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-3e774225-3088-4390-849c-7f621ecb8ae0
status:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  phase: Bound
root@i-os8hfxab:~/stone
$ kubectl get sc nfs-client -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: nfs-client-provisioner
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubesphere.io/support-snapshot: "false"
  creationTimestamp: "2020-09-22T07:47:46Z"
  labels:
    app: nfs-client-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-client-provisioner-1.2.8
    heritage: Helm
    release: nfs-client-provisioner
  name: nfs-client
  resourceVersion: "70982"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/nfs-client
  uid: a1a0b886-bc0d-45e8-931d-89f3c536942f
parameters:
  archiveOnDelete: "true"
provisioner: cluster.local/nfs-client-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
root@i-os8hfxab:~/stone
$ nfsstat -m
/var/lib/kubelet/pods/3333727d-24f8-4b78-b1a7-1fc44125afb2/volumes/kubernetes.io~nfs/nfs-client-root from 192.168.0.27:/mnt/csi
 Flags:	rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.0.40,local_lock=none,addr=192.168.0.27

/var/lib/kubelet/pods/e6774bb2-87e9-4a69-9717-6c599a8978bb/volumes/kubernetes.io~nfs/pvc-3e774225-3088-4390-849c-7f621ecb8ae0 from 192.168.0.27:/mnt/csi/default-nfs-rom-pvc-3e774225-3088-4390-849c-7f621ecb8ae0
 Flags:	rw,relatime,vers=4.1,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.0.40,local_lock=none,addr=192.168.0.27

```

**Comment by stoneshi-yunify** [comment]
And ReadWriteOnce does not work either, a PVC with ReadWriteOnce provisioned by nfs-client-provisioner can be mounted to 2 pods, this isn't right.

**Comment by yonatankahana** [comment]
> A volume’s AccessModes are descriptors of the volume’s capabilities. They are not enforced constraints. The storage provider is responsible for runtime errors resulting from invalid use of the resource.

this is a common misunderstanding of what the access modes are.
those modes are for matching between PVC's and PV's. nfs support RWO/RWX/ROX but doesn't enforce them. it just one of it's capabilities.

**Comment by yonatankahana** [comment]
this is a common misunderstanding of what the access modes are.
those modes are for matching between PVC's and PV's. nfs support RWO/RWX/ROX but doesn't enforce them. it just one of it's capabilities.

> A volume’s AccessModes are descriptors of the volume’s capabilities. They are not enforced constraints. The storage provider is responsible for runtime errors resulting from invalid use of the resource.

if you want to enforce read only on a volume, a good way is to set `readOnly: true` in your pod's `volumeMounts`.

```yaml
spec:
  containers:
  - name: my-container
    image: busybox
    volumeMounts:
    - name: datadir
      mountPath: "/data"
      readOnly: true
```

**Comment by stoneshi-yunify** [comment]
Thanks for the explanation and suggestion @yonatankahana !

**Comment by prashanthb-ai** [comment]
@yonatankahana I think this issue is still useful. Any idea what's required to support ROX? I want to ensure users don't clobber a dataset I export. Rather than trusting them to set RO on their containers, I'd rather export the data as RO. I want to force them to snapshot before editing. Any idea how this might be achieved?

**Comment by yonatankahana** [comment]
I did not get to test it yet but i believe we can add `ro` flag to the PV mountOptions when `ROX` is required and it should cause it to be mounted as read only always.

just note that it is not possible to use the current mountOptions field in the helm chart because these flags also apply to the provisioner itself and if you put `ro` there it will not be able to create folders...

what do you think @kmova @wongma7, acceptable solution?
