### ISSUE TITLE
Can't connect to Pod/container using rsh

### ISSUE THREAD

**Issue by berthomas** [kubernetes-sigs/nfs-subdir-external-provisioner#180]
Hello,

I tried to connect to the pod or container in the pod using "oc rsh" with no success.
The returned error is : 
> ERRO[0000] exec failed: container_linux.go:367: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory command terminated with exit code 1

I understand that there is no shell inside the container but is there a way install the nfs provisioner with a shell inside?
I need that because i'm not root on the NFS, so i can't delete some logs files.
Thanks for the help.

Bertrand

**Comment by seru333** [comment]
I am having this issue as well and my solution was to make a custom container and manually load it but when following the README instructions it fails because one of the vendor imports has changed and no longer has the function helper.GetPersistentVolumeClass
