### ISSUE TITLE
GetPersistentVolumeClass function removed from local vendor copy of https://github.com/kubernetes/kubernetes.git

### ISSUE THREAD

**Issue by seru333** [kubernetes-sigs/nfs-subdir-external-provisioner#183]
cmd/nfs-subdir-external-provisioner/provisioner.go imports k8s.io/client-go/kubernetes for certain functions, one is helper.GetPersistentVolumeClass and that function has been removed in the kubernetes update commit 20 days ago. This is needed to make build local and prevents creating a new docker image with bash capabilities.

**Comment by cheeye** [comment]
the same issue here
