### ISSUE TITLE
Is there a solution to the provisioned storage limit

### ISSUE THREAD

**Issue by zidoshare** [kubernetes-sigs/nfs-subdir-external-provisioner#186]
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
    min:
      storage: 1Gi

**Comment by koraykutanoglu** [comment]
hi, i need this too. I've been working on this lately. As a result of my research, I came to the conclusion that we need to configure the NFS server machine as XFS. However, it still needs help. How can we set a quota for PVC?

**Comment by npu21** [comment]
hi @koraykutanoglu Does that mean this project doesn't support quota for PVC?

**Comment by koraykutanoglu** [comment]
@npu21 yes it looks like that now. The quota cannot be set when you connect a PVC using NFS.

**Comment by alex-g-tejada** [comment]
Hey everyone,

curious about this too, is there a way to monitor and limit this kind of usage?
