### ISSUE TITLE
Wrong ServiceAccount name in README for OpenShift

### ISSUE THREAD

**Issue by yonatankahana** [kubernetes-sigs/nfs-subdir-external-provisioner#195]
In the readme we give command to assign SCC to service account:

```console
oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:$NAMESPACE:nfs-client-provisioner
```

but in the helm chart we renamed the SA to `nfs-subdir-external-provisioner` long time ago.

to make it work, we need to change it to:

```console
oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:$NAMESPACE:nfs-subdir-external-provisioner
```

maybe different documentation for helm is required.

**Comment by MallocArray** [comment]
Agreed this is still an issue in the main README and is completely lacking in the helm chart README file
