### ISSUE TITLE
Can multiple Storage classes be created?

### ISSUE THREAD

**Issue by cheepsoot** [kubernetes-sigs/nfs-subdir-external-provisioner#201]
Hello,

I am wanting to create two different storageclasses with different types of storage(hdd, ssd), and I am wondering how this might be done using this external provisioner.  Can this be done by creating an additional storageclass or maybe an additional volume??  Or maybe somehow creating a new instance of the "nfs-client-provisioner"??  

Thank for your response in advance.

**Comment by yonatankahana** [comment]
yes - it can be done. you can export multiple paths in your nfs server(s) and install as many provisioners as needed, you can read more about it in the documentation about how to [Install Multiple Provisioners](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/charts/nfs-subdir-external-provisioner#install-multiple-provisioners).

**Comment by PraveenJP** [comment]
@yonatankahana without helm do you have any reference to install?

**Comment by cheepsoot** [comment]
Thank you for the quick response!  I will give your link a read.  Much appreciated 😊
