### ISSUE TITLE
Support restoring a volume

### ISSUE THREAD

**Issue by cornfeedhobo** [kubernetes-sigs/nfs-subdir-external-provisioner#204]
### What I want

I'd like to be able to destroy a StatefulSet, then optionally un-archive the previous PVC directory and use it to satisfy the claim for a new StatefulSet.

### What currently happens

I have to re-populate manually on the NFS server

**Comment by BloodyIron** [comment]
Yeah I'd like some sort of automatic mechanism to auto-unarchive or something like that.

**Comment by BloodyIron** [comment]
I've honestly just switched to csi-driver-nfs, and I appreciate this project existing as an option, but the dynamic-only method here doesn't work for me. And it sure looks like there's no motivation for that to change for this project. Oh well.
