### ISSUE TITLE
Migrating from efs-provisioner

### ISSUE THREAD

**Issue by tobias-zeptio** [kubernetes-sigs/nfs-subdir-external-provisioner#23]
Deploying the now deprecated [efs-provisioner](https://github.com/helm/charts/tree/master/stable/efs-provisioner) leads you here as a replacement, but there is no migration path.

What I see as the only issue right now is that there is a required NFS_SERVER address, while EFS has one IP per Availability Zone. I've been working with kubernetes for years, but I'm new to AWS.

I tried using `file-system-id.efs.aws-region.amazonaws.com` as NFS_SERVER, but I get a `mount failed: exit status 32` during scheduling.

**Comment by jellevanhees** [comment]
we are looking to solve the same problem. 
the actual go tool here is updated recently but the "latest" container hosted by quay is over 2 years old.
making nfs-provisioner newer than this.
the biggest issue of this repo that it doesn't have a ci/cd build container. 
if someone can help met set this up using github tools for building the container we could try to push an up to date container to quay or public ecr.

**Comment by tobias-zeptio** [comment]
I see, are you using this to successfully mount EFS volumes?

Unfortunately, I've never used github CI tools.

**Comment by jellevanhees** [comment]
we are currently using efs-provisioner which is a helm chart containing a deprecated version of this tool.
I will see if i can find some time to work on getting this container build using github actions.

**Comment by Routhinator** [comment]
I believe the appropriate migration path for EFS is to mount the EFS storage via the universal DNS name and not the AZ specific name as per this documentation: https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html 

> File system DNS name – Using the file system's DNS name is your simplest mounting option. The file system DNS name automatically resolves to the mount target’s IP address in the Availability Zone of the connecting Amazon EC2 instance. You can get this DNS name from the console, or if you have the file system ID, you can construct it using the following convention.

`file-system-id.efs.aws-region.amazonaws.com`

There is also `availability-zone.file-system-id.efs.aws-region.amazonaws.com` for when you want to mount the filesystem from a *specific* az target for servers that live exclusively in that AZ, but for this you want the common name that will resolve to the local mountpoint and allow for seamless failover.

**Comment by Routhinator** [comment]
So I have tested this now - and it is working flawlessly for me.

Relevant terraform for the setup:

```hcl
resource "aws_efs_file_system" "eks-volumes" {
   creation_token = "eks-volumes"
   performance_mode = "generalPurpose"
   throughput_mode = "bursting"
   encrypted = "true"
   tags = {
     Name = "EKSVolumes"
   }
}

resource "aws_efs_mount_target" "eks-volumes-ca-central-1a" {
  file_system_id = aws_efs_file_system.eks-volumes.id
  subnet_id      = module.vpc.private_subnets.0

  security_groups = [
    aws_security_group.efs-target-eks-volumes.id
  ]
}

resource "aws_efs_mount_target" "eks-volumes-ca-central-1b" {
  file_system_id = aws_efs_file_system.eks-volumes.id
  subnet_id      = module.vpc.private_subnets.1

  security_groups = [
    aws_security_group.efs-target-eks-volumes.id
  ]
}

resource "aws_security_group" "efs-target-eks-volumes" {
  name        = "efs-target-eks-volumes"
  description = "Allows NFS traffic from instances within the VPC."
  vpc_id      = module.vpc.vpc_id

  ingress {
    from_port = 2049
    to_port   = 2049
    protocol  = "tcp"
    cidr_blocks = ["172.16.1.0/25", "172.16.1.128/25"]
  }

  egress {
    from_port = 2049
    to_port   = 2049
    protocol  = "tcp"
    cidr_blocks = ["172.16.1.0/25", "172.16.1.128/25"]
  }
}

resource "helm_release" "nfs-subdir-external-provisioner" {
  depends_on = [
    aws_efs_mount_target.eks-volumes-ca-central-1a,
    aws_efs_mount_target.eks-volumes-ca-central-1b
  ]
  name       = "nfs-subdir-external-provisioner"
  chart      = "nfs-subdir-external-provisioner"
  repository = "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
  version    = "4.0.3"
  namespace  = kubernetes_namespace.storage-deployments.metadata.0.name

  set {
    name  = "nfs.server"
    value = aws_efs_file_system.eks-volumes.dns_name
  }

  set {
    name  = "nfs.path"
    value = "/"
  }

  set {
    name  = "storageClass.name"
    value = "efs-client"
  }
}
```

**Comment by tobias-zeptio** [comment]
The info provided by @Routhinator was enough for me to migrate.
