### ISSUE TITLE
question about tag of image k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner

### ISSUE THREAD

**Issue by hillbun** [kubernetes-sigs/nfs-subdir-external-provisioner#231]
I can just pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2

How to pull other version 4.0.17, 4.0.16, 4.0.15...?

**Comment by hillbun** [comment]
any advice?

**Comment by yokaimeow** [comment]
[4.0.17 Releases](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/download/nfs-subdir-external-provisioner-4.0.17/nfs-subdir-external-provisioner-4.0.17.tgz)

``` values.yaml
image:
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
imagePullSecrets: []
```

tag version is v4.0.2

**Comment by hillbun** [comment]
tag version is always v4.0.2?

**Comment by hillbun** [comment]
Can anyone give advice about image tag rule?

**Comment by rmoreas** [comment]
Versions 4.0.17, 4.0.16, 4.0.15.. are versions of the helm chart, appVersion is still 4.0.2. See https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/Chart.yaml.

**Comment by hillbun** [comment]
do you mean this image of k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner version do not upgrade when new release https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases here?

**Comment by yokaimeow** [comment]
Yes,image version is still 4.0.2

**Comment by hillbun** [comment]
how to get new version then?   if new feather released or bug fixed

**Comment by rmoreas** [comment]
When there is a new version, the appVersion and image tag will be updated in the helm chart and the helm chart itself also get a version bump.

**Comment by hillbun** [comment]
this repo release version is nfs-subdir-external-provisioner-4.0.17, but image tag is still 4.0.2.

How to update image tag version.

**Comment by rmoreas** [comment]
@hillbun : see comments https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/231#issuecomment-1232630549, https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/231#issuecomment-1235679775

**Comment by hillbun** [comment]
@rmoreas   But I still do not understand how to upgrade image version to latest but not 4.0.2

please advice.

**Comment by guilhermemalfatti** [comment]
@hillbun   v4.0.2 is the latest version.
