### ISSUE TITLE
variable subtitution in pathPattern

### ISSUE THREAD

**Issue by AskAlice** [kubernetes-sigs/nfs-subdir-external-provisioner#234]
I was hoping to use an annotation at times, but other times I would like it to fall back and instead use the pvc name.
```yaml
pathPattern: "$${.PVC.namespace}-$${.PVC.annotations.nfs.io/storage-path}"
```

or if the annotation is unset,
```yaml

pathPattern: "$${.PVC.namespace}-$${.PVC.name}"
```

**Comment by smuda** [comment]
Yes, this would be a great thing!
