### ISSUE TITLE
Understanding Question

### ISSUE THREAD

**Issue by sassyn** [kubernetes-sigs/nfs-subdir-external-provisioner#235]
I just wonder what I'm missing here:

Say I have a master and a worker + NFS Server (we will call it storage)

Master and Worker have the NFS volume mount (via /etc/fstab) in /mnt/Storage.

What If I create the Persistent Volume in  /mnt/Storage?  Then to my understanding I don't need this addon.

If that is true, than what is the value of this module? 
The only thing I can figure is that with the module the /mntStoage not needed to be mounted on the host.

What I'm missing? Thank You

**Comment by eumel8** [comment]
The value is to have a NFS server "somewhere", like a Netapp or a Cloud NFS Service where this NFS client can connect to and the user can use this storage in a Kubernetes resource (PVC), provided by the StorageClass `nfs-client`
