### ISSUE TITLE
Provisioned PVs get a name which doesn't match the docs or the `pathPattern`

### ISSUE THREAD

**Issue by WoodyWoodsta** [kubernetes-sigs/nfs-subdir-external-provisioner#237]
When I create a PVC, the resulting PV is named `pvc-<uuid>` (for example, `pvc-2c1ac3ff-91d3-43eb-8fc9-48516629f44a`.

Setting `storageClass.pathPattern` (in the helm values) to `${.PVC.namespace}-${.PVC.name}` makes no difference.

Expected behaviour is deterministic and static PV names so that they can be referenced in PVCs across namespaces.

**Comment by nabiltntn** [comment]
@WoodyWoodsta I think the pattern is for the name of the subdirectory that will be created for the volume under the NFS share and not the name of the name PV resources.

**Comment by WoodyWoodsta** [comment]
@nabiltntn That makes sense, thank you.
