### ISSUE TITLE
Error Pulling image from docker and kubernetes - Not Found.

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes-sigs/nfs-subdir-external-provisioner#239]
The docker attempt is from a totally different machine on a totally different network.  They are not even in the same datacenter.

I tried different versions as well.

docker pull k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17
`
Error response from daemon: manifest for k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17 not found: manifest unknown: Failed to fetch "v4.0.17" from request "/v2/sig-storage/nfs-subdir-external-provisioner/manifests/v4.0.17".
`
from kubernetes:
`
Failed to pull image "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17": failed to resolve reference "k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17": k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.17: not found
`

**Comment by Daxcor69** [comment]
newest available image is 4.0.2. Can you fix this please.

**Comment by lievendp** [comment]
It appears I have the same issue, this is coming from K3s helm trying to get the same:
`+ helm_v3 repo add --ca-file /config/ca-file.pem nfs https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
"nfs" has been added to your repositories
+ helm_v3 repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nfs" chart repository
Update Complete. ⎈Happy Helming!⎈
+ helm_update install --namespace default --repo https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner --set-string nfs.path=/<SOME_PATH> --set-string nfs.server=<SOME_IP> --set-string storageClass.name=nfs --set-string storageClass.reclaimPolicy=retain
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ tr '[:upper:]' '[:lower:]'
++ jq -r '"\(.[0].app_version),\(.[0].status)"'
++ helm_v3 ls --all -f '^nfs$' --namespace default --output json
+ LINE=null,null
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ [[ install = \d\e\l\e\t\e ]]
+ [[ null =~ ^(|null)$ ]]
+ [[ null =~ ^(|null)$ ]]
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace default --repo https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner --set-string nfs.path=/<SOME_PATH> --set-string nfs.server=<SOME_IP> --set-string storageClass.name=nfs --set-string storageClass.reclaimPolicy=retain nfs nfs-subdir-external-provisioner --ca-file /config/ca-file.pem
Error: INSTALLATION FAILED: failed to download "https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/download/nfs-subdir-external-provisioner-4.0.17/nfs-subdir-external-provisioner-4.0.17.tgz"
`

I'm not much of a programmer and getting used to K3s/kubernetes in general, let me know if there's anything I can do to help this?

Thanks and kind regards.

**Comment by yonatankahana** [comment]
> It appears I have the same issue, this is coming from K3s helm trying to get the same:
> 
> ```
> `+ helm_v3 repo add --ca-file /config/ca-file.pem nfs https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
> "nfs" has been added to your repositories
> + helm_v3 repo update
> Hang tight while we grab the latest from your chart repositories...
> ...Successfully got an update from the "nfs" chart repository
> Update Complete. ⎈Happy Helming!⎈
> + helm_update install --namespace default --repo https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner --set-string nfs.path=/<SOME_PATH> --set-string nfs.server=<SOME_IP> --set-string storageClass.name=nfs --set-string storageClass.reclaimPolicy=retain
> + [[ helm_v3 == \h\e\l\m\_\v\3 ]]
> ++ tr '[:upper:]' '[:lower:]'
> ++ jq -r '"\(.[0].app_version),\(.[0].status)"'
> ++ helm_v3 ls --all -f '^nfs$' --namespace default --output json
> + LINE=null,null
> + IFS=,
> + read -r INSTALLED_VERSION STATUS _
> + VALUES=
> + [[ install = \d\e\l\e\t\e ]]
> + [[ null =~ ^(|null)$ ]]
> + [[ null =~ ^(|null)$ ]]
> + echo 'Installing helm_v3 chart'
> + helm_v3 install --namespace default --repo https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner --set-string nfs.path=/<SOME_PATH> --set-string nfs.server=<SOME_IP> --set-string storageClass.name=nfs --set-string storageClass.reclaimPolicy=retain nfs nfs-subdir-external-provisioner --ca-file /config/ca-file.pem
> Error: INSTALLATION FAILED: failed to download "https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/download/nfs-subdir-external-provisioner-4.0.17/nfs-subdir-external-provisioner-4.0.17.tgz"
> `
> ```
> 
> I'm not much of a programmer and getting used to K3s/kubernetes in general, let me know if there's anything I can do to help this?
> 
> Thanks and kind regards.

You have different issue, probably connection problem since the link https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/download/nfs-subdir-external-provisioner-4.0.17/nfs-subdir-external-provisioner-4.0.17.tgz is valid.

**Comment by yonatankahana** [comment]
> newest available image is 4.0.2. Can you fix this please.

There is nothing to fix since the latest provisioner image is 4.0.2. Not to confuse with helm chart versions.

/close
