### ISSUE TITLE
Error getting server version error in  nfs-subdir-external-provisioner

### ISSUE THREAD

**Issue by Abhilash-as** [kubernetes-sigs/nfs-subdir-external-provisioner#242]
Issue
![image](https://user-images.githubusercontent.com/28435089/196693753-0dbc8836-a122-44fb-b987-0a47936b8089.png)

Log

![image](https://user-images.githubusercontent.com/28435089/196694271-b21e7b22-6f27-4683-8dd0-086b0b156204.png)

While doing curl request  its working
![image](https://user-images.githubusercontent.com/28435089/196694520-d95dd6a7-effc-4e5a-a674-7ccfff5cd75e.png)

**Helm version :- 3.10.1**
Chart:- [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)

**What happened:**
CrashLoopBackOff occured for nfs-subdir-external-provisioner

**What you expected to happen:**
 nfs-subdir-external-provisioner running and ready
 
 **How to reproduce it :**
Occurred during the first time installation itself

Note:- **The pod network range while kubeadm init and Calico network are same**

**Comment by joeltraber** [comment]
any news on this one? (I face the same)
thx!

**Comment by Abhilash-as** [comment]
@joeltraber Actually we didn't got any solution. Everywhere we have seen like its the issue with calico network. The difference between CIDR range in Calico and Pod network. But that was same for us. We was using CentOS 8 and found some difference in iptables. So we changed back to CentOS 7 and reinstalled cluster, that time it worked.
