### ISSUE TITLE
Provisioner cannot start or mount any NFS share after upgrading cluster

### ISSUE THREAD

**Issue by donicrosby** [kubernetes-sigs/nfs-subdir-external-provisioner#244]
I had a cluster running on 1.20.x (NFS Provisioner worked fine) I upgraded it to 1.24.x after the rollout no NFS shares could no longer be mounted.

Post upgrade when any pod tried to mount the NFS PVs provisioned by the provisioner they all failed. This is the error message from the provisioner deployment:

```
MountVolume.SetUp failed for volume "pv-nfs-client-provisioner-nfs-subdir-external-provisioner" : mount failed: exit status 32 
Mounting command: mount Mounting arguments: -t nfs -o nfsvers=4.0 172.16.0.17:/export/Kubernetes /var/lib/kubelet/pods/a51e63d4-2577-433e-a1c6-016046c3df8e/volumes/kubernetes.io~nfs/pv-nfs-client-provisioner-nfs-subdir-external-provisioner 
Output: mount.nfs: mounting 172.16.0.17:/export/Kubernetes failed, reason given by server: No such file or directory
```

The NFS server is a bare-metal NFS server on the same local network as the k8s worker nodes. What's weirder is that I _can_ mount the exported folder when I ssh into the worker boxes (all of them). But for some reason either kubelet or the provisioner can't seem to figure out how to access the NFS share post upgrade.

![image](https://user-images.githubusercontent.com/16298520/200096911-690a4973-8bdb-4b2f-abd7-597b352c0870.png)

Was there something that changed in how either the provisioner now works within the upgraded APIs or is this strictly a kubelet thing? If it is a change in kubelet what would be the best repo for getting support for this?

**Comment by mblixter** [comment]
I'm having the exact same issue. It works fine in a v1.24.4 K8s cluster, but I'm getting the same error as reported here in a k8s v1.24.6.
Logging into the worker node, I can see that the path(/var/lib/kubelet/pods/a51e63d4-2577-433e-a1c6-016046c3df8e/volumes/kubernetes.io~nfs/pv-nfs-client-provisioner-nfs-subdir-external-provisioner) does indeed not exist. Trying to manually create the path and then re-deploying does not help, still same error?

Any ideas?

**Comment by onahkenneth** [comment]
@mblixter I have exactly the same issue like you except I am using a v1.21.3 k3s cluster
