### ISSUE TITLE
changing PVName template

### ISSUE THREAD

**Issue by teonius** [kubernetes-sigs/nfs-subdir-external-provisioner#248]
hi, i was looking through the documentation but i couldnt find anything about this
is it possible to do adjustments to the PV-Name template?  currently its pvc-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
my goal is to have "${pvc.name}-pv"   (or something similar)

if i missed this in another discussion sorry for the double post

**Comment by BennyAfriat** [comment]
Im also looking for a solution for this problem

**Comment by smuda** [comment]
Isn't this what the [parameter pathPattern is for](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/README.md)?

**Comment by d-uzlov** [comment]
`pathPattern` configures mounted folder path on the NFS server.
It does not affect PV name.
Also, the rules for folder path and for PV name are different.
