### ISSUE TITLE
Protocal not supported

### ISSUE THREAD

**Issue by abhinav1144** [kubernetes-sigs/nfs-subdir-external-provisioner#251]
MountVolume.SetUp failed for volume "nfs-subdir-external-provisioner-root" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t nfs server-name:path  /var/lib/kubelet/pods/543b5aaf-b62e-4ede-a411-24104272a76a/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root Output: mount.nfs: Protocol not supported

**Comment by dangllucas** [comment]
This is not a Problem with the nfs-subdir-external-provisioner.
It just states, that your underlying OS on your nodes does not support the nfs Protocol to perform a mount.

On Debian Based OS install `nfs-common` (`sudo apt-get install -y nfs-common`).

You can test nfs Mounts by using the following command on your nodes: `mount -t nfs <host>:/<mount-path> <local-path>` to ensure, that the nfs protocol is supported.
