### ISSUE TITLE
node affinity documentation 

### ISSUE THREAD

**Issue by deeco** [kubernetes-sigs/nfs-subdir-external-provisioner#253]
its not clear if node affinity is supported and how can be labeled or setup. 

Example would be like https://github.com/openebs/dynamic-nfs-provisioner/blob/develop/docs/tutorial/node-affinity.md

Here a custom label can be assigned to nodes and only specfic provisioner is used. this is useful in the case of multiple datacentres where there are nfs / nas located with nodes

**Comment by mattrpav** [comment]
Deploying as a DaemonSet may be more appropriate

related: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/177
