### ISSUE TITLE
FailedCreatePodSandBox

### ISSUE THREAD

**Issue by java-software** [kubernetes-sigs/nfs-subdir-external-provisioner#257]
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Normal   Scheduled               7d18h               default-scheduler  Successfully assigned a/nfs-client-provisioner-59c5f46f5-d4nds to work01
  Warning  FailedCreatePodSandBox  101s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cb8a846be7902a752bae7f4cdee280111ba8f005e90b6b68c7062bd1cb68a7b4": plugin type="calico" failed (add): connection is unauthorized: Unauthorized
  Normal   SandboxChanged          11s (x8 over 100s)  kubelet            Pod sandbox changed, it will be killed and re-created.

**Comment by yonatankahana** [comment]
@java-software it seems to be a problem in your cluster and not necessarily related to nfs-subdir-external-provisioner.

/close
