### ISSUE TITLE
"pvc.used" takes space-used of nfs.path wrongly

### ISSUE THREAD

**Issue by ronnin** [kubernetes-sigs/nfs-subdir-external-provisioner#259]
All the PVC provisioned by this provisioner,  will meet error "disk out of space" when space-used of nfs.path exceeds the capacity of pvc.

eg.
The nfs.path, /srv/nfs, has 500G capacity, and 150G used.
These PVC, pvc1 with 3G capacity and 1G used, pvc2 with 5G capacity and 1G used, pvc3, with 100G capacity and 5G used, meet error "disk out of space" all.

**Comment by yonatankahana** [comment]
@ronnin Can you please provide more information? It is not very clear...

**Comment by ronnin** [comment]
- ### A PVC provisioned by this provisioner:

![image](https://user-images.githubusercontent.com/100691/219931320-310e3b30-5e62-45d6-939a-aeab905a6f78.png)
- ### Another PVC provisioned by this provisioner:
![image](https://user-images.githubusercontent.com/100691/219931447-fc6b9dab-9f7b-4030-af30-00e08c0f888e.png)
- ### The Deployment of the provisioner:
![image](https://user-images.githubusercontent.com/100691/219931530-f1236f89-428f-4315-bd3a-e8cf7e8333c2.png)
- ### Real info of space used:
![image](https://user-images.githubusercontent.com/100691/219931783-2dc2bb4a-5b82-494b-96fd-434c02e3de00.png)

**Comment by nguyenle24** [comment]
got the same issue, dont know how to solve this problem
