### ISSUE TITLE
nfs-subdir-external-provisioner keeps on failing

### ISSUE THREAD

**Issue by bhavesh100ms** [kubernetes-sigs/nfs-subdir-external-provisioner#260]
We are facing an issue on OKE(Orcale Kubernetes Engine). NFS provisioners pods keeps restarting with below error
`
I0120 04:15:12.604497       1 leaderelection.go:242] attempting to acquire leader lease  nfs-storage/cluster.local-nfs-subdir-external-provisioner...
I0120 04:15:32.653560       1 leaderelection.go:252] successfully acquired lease nfs-storage/cluster.local-nfs-subdir-external-provisioner
I0120 04:15:32.653661       1 event.go:278] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"nfs-storage", Name:"cluster.local-nfs-subdir-external-provisioner", UID:"8f33cb75-65c3-4434-89a2-2330e9e030fd", APIVersion:"v1", ResourceVersion:"59358381", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' nfs-subdir-external-provisioner-6df4bffc7f-kmjhx_8c841ddd-3207-4c62-9eb6-9fd79d23cb71 became leader
I0120 04:15:32.654059       1 controller.go:820] Starting provisioner controller cluster.local/nfs-subdir-external-provisioner_nfs-subdir-external-provisioner-6df4bffc7f-kmjhx_8c841ddd-3207-4c62-9eb6-9fd79d23cb71!
I0120 04:15:32.754247       1 controller.go:869] Started provisioner controller cluster.local/nfs-subdir-external-provisioner_nfs-subdir-external-provisioner-6df4bffc7f-kmjhx_8c841ddd-3207-4c62-9eb6-9fd79d23cb71!
E0120 05:04:30.123720       1 leaderelection.go:320] error retrieving resource lock nfs-storage/cluster.local-nfs-subdir-external-provisioner: Get "https://10.96.0.1:443/api/v1/namespaces/nfs-storage/endpoints/cluster.local-nfs-subdir-external-provisioner": context deadline exceeded
I0120 05:04:30.124121       1 leaderelection.go:277] failed to renew lease nfs-storage/cluster.local-nfs-subdir-external-provisioner: timed out waiting for the condition
F0120 05:04:30.124134       1 controller.go:898] leaderelection lost
I0120 05:04:30.124696       1 event.go:278] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"", Name:"", UID:"", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' nfs-subdir-external-provisioner-6df4bffc7f-kmjhx_8c841ddd-3207-4c62-9eb6-9fd79d23cb71 stopped leading
`

Kubernetes version: 1.24
Are we missing any things. Do we need to add some flags ?

**Comment by yonatankahana** [comment]
Hi @bhavesh100ms,
It seems to be a problem related to leader election. You can try to disable it from [helm values](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/4c82f69eefaa06e1200a165e5f64f6de0e57c796/charts/nfs-subdir-external-provisioner/values.yaml#L62) i.e `--set leaderElection.enabled=false`.

**Comment by myysophia** [comment]
oh , I have seem problem.
![image](https://user-images.githubusercontent.com/25994521/233653378-c1020f6f-37ed-429f-8ab3-59b21685408b.png)
