### ISSUE TITLE
Access Denied by server while mounting

### ISSUE THREAD

**Issue by kejvi-doko** [kubernetes-sigs/nfs-subdir-external-provisioner#262]
I have configured an NFS server and mounted on control-plane and 2 worker nodes using the following command:

```
sudo mount x.x.x.x:/mnt/nfs_share /mnt/nfs_clientshare
```
When I install the storage provisioner, pod i stuck on ContainerCreating and from the describe command I see the following error: 

```
Mounting arguments: -t nfs x.x.x.x:/mnt/nfs_clientshare /var/lib/kubelet/pods/6a95b73f-732a-444c-882b-ce69e4cada88/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root
Output: mount.nfs: access denied by server while mounting x.x.x.x:/mnt/nfs_clientshare
```

NFS Exports File: 

```
# /etc/exports: the access control list for filesystems which may be exported
#		to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
#

/mnt/nfs_share *(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)
```

Mount Folder Permission on Control-Plane and Worker Nodes
```
$:~# ls -al /mnt/
total 12
drwxr-xr-x  3 root   root    4096 Jan 26 02:16 .
drwxr-xr-x 20 root   root    4096 Jan 26 00:53 ..
drwxrwxrwx  2 nobody nogroup 4096 Jan 31 00:55 nfs_clientshare
```

**Comment by yonatankahana** [comment]
you have set the `nfs.path` to `/mnt/nfs_clientshare` instead of `/mnt/nfs_share`

**Comment by bjelac** [comment]
Hi, I have a same Issue but with correct path.
NFS Shere is hosted on Synology DS415+ and I can mount share with:
`sudo mount -t nfs -o hard 192.168.1.199:/volume1/kubernetes testnfs` 
NAS supports NSFv2, NSFv3 and NSFv4. Max Suported NSF Protocol is set to NSFv4 on NAS.
I install the storage provisioner with:
`helm install --kubeconfig=$KUBE_CONFIG nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server=192.168.1.199 --set nfs.path=/volume1/kubernetes`
The Pod stucks on ContainerCreating and from the describe command I see the following error:
```
Mounting command: mount
Mounting arguments: -t nfs 192.168.1.199:/volume1/kubernetes /var/lib/kubelet/pods/fdc475dc-7faa-48b6-8e61-e55884f8c308/volumes/kubernetes.io~nfs/nfs-subdir-external-provisioner-root
Output: mount.nfs: access denied by server while mounting 192.168.1.199:/volume1/kubernetes
```
What could be an Issue? Thanks.
