### ISSUE TITLE
Helm Chart update

### ISSUE THREAD

**Issue by panis16** [kubernetes-sigs/nfs-subdir-external-provisioner#264]
Is it possible to update Helm Chart with latest onDelete fixes?

Thx.

**Comment by aek-arm** [comment]
Seem to be that the project is lacking contributors so I don't think so. At least in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/205#issuecomment-1137655769 a way to use a newer image is mentioned.
