### ISSUE TITLE
k8s stoped

### ISSUE THREAD

**Issue by HeWeiGitHub** [kubernetes-sigs/nfs-subdir-external-provisioner#265]
have other error，k8s is stop：
root@ubuntu-one:/nfs# gedit /etc/kubernetes/manifests/kube-apiserver.yaml
root@ubuntu-one:/nfs# kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?
root@ubuntu-one:/nfs# kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?
root@ubuntu-one:/nfs# kubectl get pods
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?

**Comment by yonatankahana** [comment]
not related to nfs-subdir-external-provisioner

/close
