### ISSUE TITLE
in k8s v1.26.1 add that config，but will have new error，that k8s start faild

### ISSUE THREAD

**Issue by HeWeiGitHub** [kubernetes-sigs/nfs-subdir-external-provisioner#266]
root@ubuntu-one:/nfs# gedit /etc/kubernetes/manifests/kube-apiserver.yaml
root@ubuntu-one:/nfs# kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?
root@ubuntu-one:/nfs# kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?
root@ubuntu-one:/nfs# kubectl get pods
The connection to the server ubuntu-one:6443 was refused - did you specify the right host or port?

**Comment by yonatankahana** [comment]
not related to nfs-subdir-external-provisioner

/close
