### ISSUE TITLE
StorageClass reclaimPolicy and onDelete parameters

### ISSUE THREAD

**Issue by gjumic-optiva** [kubernetes-sigs/nfs-subdir-external-provisioner#268]
Hi all.

In my cluster I have deployed nfs-provisioner with the following values:

```
storageClass.reclaimPolicy = Retain
storageClass.onDelete = delete
```

My expectation was when Pod and PVC are deleted that PV and data on the NFS share will persist, and by deleting PV nfs-provisioner will delete data on the NFS share. In a nutshell, I need a solution for data to persist in NFS share until the actual PV is deleted.

This does not happen, when reclaimPolicy is set to "Retain" onDelete = delete does nothing.

Is my expected behavior even possible?

Note that I have built my own container image due to the latest release being pretty outdated.

**Comment by xjezzuuuu** [comment]
I have the same problem, the idea is that when declaring the ReclaimPolicy in Retain, the pv or the onDelete parameter can be used again: retain
