### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[export], unattached volumes=[minio-config-dir kube-api-access-tdj44 export]: timed out waiting for the condition

### ISSUE THREAD

**Issue by linpanru** [kubernetes-sigs/nfs-subdir-external-provisioner#269]
![image](https://user-images.githubusercontent.com/56077231/221836544-725503ef-f929-4eef-a7a4-9936bfff5114.png)
at the beginning, all is ready ,but one day ,the nfs server is down, so i change the another nfs server address; now , nfs-client-provisioner is ready, but my other pod use nfs pvc restart occuer this error , what can i do

**Comment by yonatankahana** [comment]
Hi @linpanru,
Changing the IP on the provisioner did not help because the PersistentVolume for your pod(s) already provisioned and unfortunately, once they created they cannot be changed.
AFAIK there is no easy solution here, if you didn't use DNS, you will probably need to recreate the PVC and re-provision the PV with the new IP (remember to backup your data first!).

**Comment by linpanru** [comment]
> Hi @linpanru, Changing the IP on the provisioner did not help because the PersistentVolume for your pod(s) already provisioned and unfortunately, once they created they cannot be changed. AFAIK there is no easy solution here, if you didn't use DNS, you will probably need to recreate the PVC and re-provision the PV with the new IP (remember to backup your data first!).

**Comment by linpanru** [comment]
> Hi @linpanru, Changing the IP on the provisioner did not help because the PersistentVolume for your pod(s) already provisioned and unfortunately, once they created they cannot be changed. AFAIK there is no easy solution here, if you didn't use DNS, you will probably need to recreate the PVC and re-provision the PV with the new IP (remember to backup your data first!).

thaks very much !
