### ISSUE TITLE
Pod keeps rebooting with the error  Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout on version 1.25

### ISSUE THREAD

**Issue by babubalagani** [kubernetes-sigs/nfs-subdir-external-provisioner#273]
k logs nfs-subdir-external-provisioner-84f4f98569-h2qwg
F0315 01:33:28.079624       1 provisioner.go:247] Error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout

Kubernetes version is  v1.25.3

**Comment by croneter** [comment]
Same here
