### ISSUE TITLE
Old or confusingly tagged version in the image repo/helm chart?

### ISSUE THREAD

**Issue by talavis** [kubernetes-sigs/nfs-subdir-external-provisioner#274]
When setting up the helm chart I noticed that the referenced tag is `v4.0.2`, while the latest release here on Github is 4.0.18. There  also seem to be no newer versions available, e.g. `v4.0.3`, `4.0.3` or `latest`.

Is the image tagged `v4.0.2` the latest release (with a confusing tag name), or am I supposed to find the image elsewhere/build it myself?

**Comment by yonatankahana** [comment]
Helm charts have `version  and `appVersion`. The `appVersion` represents the provisioner image version, and the `version` is the chart version itself. The chart version may be different than the provisioner. The latest provisioner version is indeed 4.0.2.

**Comment by talavis** [comment]
I was considering the actual tag of the image used in the pod:
```
image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
```

**Comment by yonatankahana** [comment]
Yes, you are using the latest version.

**Comment by talavis** [comment]
Thank you.
