### ISSUE TITLE
docker image update

### ISSUE THREAD

**Issue by loeken** [kubernetes-sigs/nfs-subdir-external-provisioner#281]
greetings,

Ive noticed the docker image is a bit outdated, is this image managed here?

registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2

**Comment by vogtph** [comment]
same question. current version is v4.0.18 but latest image version is v4.0.2 "Created": "2021-03-27T13:06:57.171494634Z"

**Comment by dutangp** [comment]
no luck so far?

**Comment by vogtph** [comment]
I followed the readme and created a fork and a registry on quay.io. After changing the tag in the release.yml, defining the secrets on github  and creating a tag matching the selection in the release.yml the pipeline was activated and created a new image on quay.io/paulwrr/proxy for me. Still with the alpine v3.12, still have to udate that version in the Dockerfile used.

So the pipeline works, only the tag filter should be changed to generate an official new image.

**Comment by aek-arm** [comment]
In https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/205#issuecomment-1137655769 one of the contributors links to an unofficial image that seems to be current.

**Comment by h3369** [comment]
@vogtph There is a problem with your image and it cannot run successfully. Even if I change the command to/bin/bash/bin/sh tail - f/dev/null, it cannot be used. Error message: exec/bin/sh: exec format error
