### ISSUE TITLE
failed to provision volume with StorageClass "nfs-filestorage": unable to create directory to provision new pv: mkdir /persistentvolumes/dev-rbac-pvc: input/output error

### ISSUE THREAD

**Issue by natesh1996** [kubernetes-sigs/nfs-subdir-external-provisioner#285]
Hello,

We have a IBM Cloud VPC based Openshift cluster version 4.10
We have a nfs-client-provisioner installed in it using deployment file.

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nfs-client-provisioner"},"name":"nfs-client-provisioner","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nfs-client-provisioner"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"nfs-client-provisioner"}},"spec":{"containers":[{"env":[{"name":"PROVISIONER_NAME","value":"nfs-filestorage"},{"name":"NFS_SERVER","value":"10.20.0.39"},{"name":"NFS_PATH","value":"/nfs_nextgen_filepv"}],"image":"quay.io/external_storage/nfs-client-provisioner:latest","name":"nfs-client-provisioner","volumeMounts":[{"mountPath":"/persistentvolumes","name":"nfs-client-root"}]}],"serviceAccountName":"nfs-client-provisioner","volumes":[{"name":"nfs-client-root","nfs":{"path":"/nfs_nextgen_filepv","server":"10.20.0.39"}}]}}}}
  creationTimestamp: "2020-07-29T07:35:01Z"
  generation: 9
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: default
  resourceVersion: "803047489"
  uid: 9f361480-a89c-4491-b41b-8e7e1f44cdfe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: nfs-filestorage
        - name: NFS_SERVER
          value: 10.20.0.39
        - name: NFS_PATH
          value: /nfs_nextgen_filepv
        image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        imagePullPolicy: Always
        name: nfs-client-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-client-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-client-provisioner
      serviceAccountName: nfs-client-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-client-root
        nfs:
          path: /nfs_nextgen_filepv
          server: 10.20.0.39

When we are trying to create a new PVC inside the cluster, it is failing with the error :

Generated from nfs-filestorage_nfs-client-provisioner-84b9688cc-r8xl5_07ed936d-5bad-44aa-847b-9e951e405bd1

failed to provision volume with StorageClass "nfs-filestorage": unable to create directory to provision new pv: mkdir /persistentvolumes/dev-rbac-pvc-pvc-d1e09390-5fa6-472b-b27c-793e2620dfa4: input/output error

Please help with this issue.

**Comment by maykopetersen** [comment]
This looks like a permission problem. How are your `/etc/exports`? And your `nfs_nextgen_filepv` directory permissions (print `ls -lah nfs_nextgen_filepv` from your NFS Server, please)?
