### ISSUE TITLE
Is This Project still Maintained?

### ISSUE THREAD

**Issue by pkalemba** [kubernetes-sigs/nfs-subdir-external-provisioner#286]
I see no new images in the registry, nobody seems to reply to issues.

Do you know if anybody is here to maintain this project?

**Comment by venkatamutyala** [comment]
Just learned about this project today and I was wondering the same thing. Hopefully a contributor/maintainer can chime in.

**Comment by yonatankahana** [comment]
hi @pkalemba,
yes, it is. but we need more contributors to help with issues and PR's.

hopefully a new version will be released soon, follow #291

**Comment by jeffmbarnes** [comment]
Hi @yonatankahana just looking at https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/291 I was just wondering if there is still a plan for a 4.0.3 release

**Comment by yonatankahana** [comment]
> Hi @yonatankahana just looking at #291 I was just wondering if there is still a plan for a 4.0.3 release

absolutely. Unfortunately I don't have permissions to do the release myself but I hope someone with permissions will come and help asap

@kmova @wongma7

**Comment by cdm-arm** [comment]
HI @yonatankahana - I guess you still suffer from missing permissions? It's a pity that your work is still not in master.

**Comment by lnhrdt** [comment]
@kmova @wongma7 can you help out here?

**Comment by lnhrdt** [comment]
/reopen

@yonatankahana have you had any luck outside of this issue contacting the maintainers to help with a release?
