### ISSUE TITLE
Prometheus compatible metrics

### ISSUE THREAD

**Issue by jcpunk** [kubernetes-sigs/nfs-subdir-external-provisioner#290]
It would be nice if the pod had a prometheus compatible metrics endpoint (with optional `ServiceMonitor` from helm).

**Comment by jcpunk** [comment]
I'm still interested in this

**Comment by Starttoaster** [comment]
This could be cool, but what metrics would you like to see exported?

**Comment by jcpunk** [comment]
Perhaps the volumes under management by this tool and any free space per source?  Plus the standard CPU/RAM?

**Comment by Starttoaster** [comment]
> Perhaps the volumes under management by this tool and any free space per source? Plus the standard CPU/RAM?

🤔 
This provisioner doesn't currently know or even respect the free space of available of the NFS server, so I'm not sure how that would be accomplished.

CPU/RAM sounds more like node_exporter's job than a metrics exporter built into this, to be honest.

Care to give more thoughts for either of those ideas?

**Comment by jcpunk** [comment]
I was thinking CPU/RAM usage of the nfs-subdir-external-provisioner process itself.

Maybe how many volumes were created by the provisioner?

**Comment by Starttoaster** [comment]
> I was thinking CPU/RAM usage of the nfs-subdir-external-provisioner process itself.

This is probably better off being a metric from CAdvisor or kube-state-metrics.

> Maybe how many volumes were created by the provisioner?

This metric wouldn't really be valuable to me, personally. Because number of volumes does not give a sense for disk usage of the NFS server. And for that metric even, I'd probably rather install node_exporter on the NFS server.

**Comment by jcpunk** [comment]
I don't have a great handle on what would be useful. I mostly just like observational metrics.
