### ISSUE TITLE
Latest tags not available on registry.k8s.io

### ISSUE THREAD

**Issue by pjbgf** [kubernetes-sigs/nfs-subdir-external-provisioner#292]
Trying to bump to the latest tags I noticed that they don't seem to be available within the `registry.k8s.io` registry. Is there any alternative location to pull them from?

![image](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/5452977/d4c66e2c-65f6-4f07-bb4f-2854fb310e26)

The latest version I can pull is: `registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2`.

**Comment by pjbgf** [comment]
@yonatankahana apologies for the mistake, I thought the tags on this repository had a `1-1` paring with the generated images. Only after your reply I noticed that the helm chart tags are prefixed with `nfs-subdir-external-provisioner-`.

**Comment by anuragpathak21** [comment]
> the latest version of the image is v4.0.3, the latest version of the helm chart is 4.0.18. don't confuse helm chart version with the provisioner binary version

v4.0.3 is also not available in registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
