### ISSUE TITLE
unexpected error getting claim reference: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by wan766405890** [kubernetes-sigs/nfs-subdir-external-provisioner#293]
k8s version:1.25.4

Add this line:
--feature-gates=RemoveSelfLink=false
The do this:
kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml
kubectl apply -f /etc/kubernetes/manifests/kube-apiserver.yaml

kubelet goes down and throw error

**Comment by GizzmoAsus** [comment]
hey @wan766405890, not sure if you've resolved this or not but SelfLink was removed from Kubernetes in version 1.21 so the work around won't work.

I was able to resolve this by using the image referenced in #25, I just had to update the deployment yaml in my kubernetes cluster once the helm chart had deployed it to swap out the image  and now it's working. Doesn't solve the issue but is an easy work around for my dev environment. Please note, the replacement image was last updated 3 years ago so may not be suitable for PDC environments.

The PR #258 is still pending which looks like it will also resolve this issue properly.

**Comment by yonatankahana** [comment]
@GizzmoAsus 
can you verify if problem solved in the next version rc image: `quay.io/yonatankahana/nfs-subdir-external-provisioner:v4.0.3-rc1`?

 For helm use: `--set image.repository=quay.io/yonatankahana/nfs-subdir-external-provisioner,image.tag=v4.0.3-rc1`

**Comment by GizzmoAsus** [comment]
hey @yonatankahana, switching my image out to the one you provided does indeed work just fine.

For reference, I'm running a Kubernetes cluster @ v1.27.4

**Comment by yonatankahana** [comment]
excellent, hopefully new version will be released soon, follow #291

**Comment by GizzmoAsus** [comment]
Brilliant, I'll keep an eye out for the release and continue using the RC in the meantime, thank you :)
