### ISSUE TITLE
Does Kubernetes 1.26 support NFSv3 ?

### ISSUE THREAD

**Issue by LuckyTyagi** [kubernetes-sigs/nfs-subdir-external-provisioner#298]
We're facing issue with using NFS version 3 with Kubernetes 1.26 in production.
Wanted to know if it is supported? Couldn’t find any such compatibility matrix to support this.
Can anyone confirm it please? Thanks!
Opened a discussion here as well: https://discuss.kubernetes.io/t/does-kubernetes-1-26-support-nfsv3/24980

We're using nfs-client-provisioner 4.0.18 and delivered a helm chart which creates a storageClass object with these mountOptions. If `nfsver` is 3 then  issue is reporting during mount.

```
mountOptions:
  - rw
  - bg
  - hard
  - nointr
{{- include "nfs-client-protocol.name" . | indent 2}}
{{- if .Values.nfsver }}
  - vers={{ .Values.nfsver }}
{{- end }}
  - timeo=600
  - rsize=1048576
  - wsize=1048576
```

**Comment by yonatankahana** [comment]
@LuckyTyagi 
what issue is reported during mount?
