### ISSUE TITLE
NFS server and permisisons

### ISSUE THREAD

**Issue by urbaman** [kubernetes-sigs/nfs-subdir-external-provisioner#300]
Hi,

Is there a best practice to set the permissions on the remote NFS server shared filesystem to make sure it will be accessible from the pods?

Thank you very much.

**Comment by maykopetersen** [comment]
I think my answer in this [issuer](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/283) ( #283 ) can help you.
