### ISSUE TITLE
No DNS resolution for NFS hostname

### ISSUE THREAD

**Issue by M-Gregoire** [kubernetes-sigs/nfs-subdir-external-provisioner#303]
Hello,

I've been able to correctly deploy the provisioner on my k3s install (Running on `aarch64`) by specifiying the NFS server using the IP address.

However, when using an external service name, or a normal DNS entry, the provisioner fails to start with the following error:
```
Mounting command: mount                                                                                                                                      
Mounting arguments: -t nfs -o nfsvers=4,tcp my.domain:/mnt/path /var/lib/kubelet/<uuid>/volumes/kubernetes.io~nfs/pv-nfs-provisioner-release-nfs-subdir-external-provisioner                                                                                                       
Output: mount.nfs: Failed to resolve server my.domain: Name or service not known   
```

Same result using `nfs-svc.infrastructure.svc.cluster.local`

I've popped a `dnsutils` pod in the same namespace, which confirms that both the service and the DNS entry point to the correct IP:
```
nslookup nfs-svc.infrastructure.svc.cluster.local
Server:		10.43.0.10
Address:	10.43.0.10#53

nfs-svc.infrastructure.svc.cluster.local	canonical name = my.domain
Name:	my.domain
Address: <IP>
```

The [chart documentation](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/charts/nfs-subdir-external-provisioner#configuration) specifies that `server` can be ip or hostname so I'm guessing DNS records are supposed to be accepted?

Any idea?

Thank you

**Comment by yonatankahana** [comment]
Hi @M-Gregoire,
Pod volume mounts are handled by the kubelet which runs on the host machine, it does not have access to in-cluster coredns domains (`*.cluster.local`). nslookup in a pod inside the cluster - does.

DNS records are supported but they are resolved by the host machine and depends on the host machine DNS configurations (see `/etc/resolv.conf`).

**Comment by M-Gregoire** [comment]
Oh, this explains a lot (and makes total sense)! Thank you.
