### ISSUE TITLE
help for support for csi snapshot

### ISSUE THREAD

**Issue by garcetto** [kubernetes-sigs/nfs-subdir-external-provisioner#318]
good afternoon,
  does it support csi snapshot?
thank you.

**Comment by tamalsaha** [comment]
https://github.com/kubernetes-csi/csi-driver-nfs

**Comment by lindhe** [comment]
@tamalsaha What do you mean? Is that a no?

**Comment by Starttoaster** [comment]
The person you're replying to doesn't even appear to be a maintainer here, so they wouldn't have the authority to tell you a "yes" or "no." But as another non-maintainer, they were obviously telling you to look at that other NFS storage driver for k8s that already supports snapshotting.

**Comment by Starttoaster** [comment]
@lindhe You thumbs downed my comment, but the fact is that this NFS driver is a single, <300 lines of code, source file that doesn't even get basic security updates over time (run the latest version of this image through a Trivy scan and you'll see how bad the current state is.) I'm just saying it's unlikely that feature gets added to this NFS provisioner. I would recommend looking at the other NFS provisioner that person linked if this provisioner doesn't already have the feature you requested.

**Comment by Starttoaster** [comment]
> Also I disagree that a non-contributor lacks the authority to tell a yes or no.

A non-maintainer quite literally lacks the authority to give a "yes" or "no" to a feature addition. A non-maintainer literally couldn't do a thing about it if the maintainer(s) lacked interest in a feature proposal, besides own their own fork of course. A non-maintainer can voice their _opinion_, but they can't force a maintainer to accept code they don't want to accept.

>  lacking the nuance to be helpful for me.

Criticism accepted, I'll try to make my help more nuanced in the future. 🙃

Have a good day too.
