### ISSUE TITLE
can you have more then one nfs server 

### ISSUE THREAD

**Issue by cchalifo999** [kubernetes-sigs/nfs-subdir-external-provisioner#321]
I was wondering is there a way to have more then one nfs server 
can you have more then one nfs server

**Comment by adriantorrie** [comment]
Perhaps this might be what you're looking for...

https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md#install-multiple-provisioners

**Comment by cchalifo999** [comment]
> Perhaps this might be what you're looking for...
> 
> https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md#install-multiple-provisioners

ty for your help

**Comment by Hr46ph** [comment]
I came here searching for an answer to a similar question. I would like a unique share for each application. They are on the same server, just a unique share. Would I have to run a provisioner (and a unique storageclass) for each share or is there a way to re-use that one provisioner and storageclass?

**Comment by cccsss01** [comment]
> I came here searching for an answer to a similar question. I would like a unique share for each application. They are on the same server, just a unique share. Would I have to run a provisioner (and a unique storageclass) for each share or is there a way to re-use that one provisioner and storageclass?

I would create a new storage class for every unique share, though, this sounds like it doesn't need the dynamic capabilities of this product and you can just use standard pv and pvcs.
