### ISSUE TITLE
No releases since 4.0.2 have docker images

### ISSUE THREAD

**Issue by jbergler** [kubernetes-sigs/nfs-subdir-external-provisioner#322]
The latest image uploaded to the documented registry is 4.0.2 (far behind the 4.0.18 latest release as of writing this)
https://explore.ggcr.dev/?repo=k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner

I did some trawling through git history and found this [PR](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/21) which changed the release workflow to only trigger on tags prefixed with `gh-` which doesn't match the tags being created when new releases are cut.

I suspect the correct fix here is to update the workflow to trigger on tags without the prefix and then either manually trigger the release for 4.0.18 or to release a new version (since there are unreleased changes anyway)

**Comment by jbergler** [comment]
@moikot & @kmova fyi as you were both involved in #21

**Comment by Orhideous** [comment]
It's still an issue. There are some unmerged PRs and release process just stuck in the limbo.

**Comment by Starttoaster** [comment]
The releases you're referring to appear to be releases for the helm chart. The actual program doesn't appear to have "releases", instead the other appears to just make tags (without creating a release for them.)

**Comment by jbergler** [comment]
Thanks @Starttoaster - you are definitely right.
Looks like 4.0.3 release is being discussed in #330 so I'll mark this as closed.
