### ISSUE TITLE
provisioning storage with pre-existing data

### ISSUE THREAD

**Issue by dart-mtucker** [kubernetes-sigs/nfs-subdir-external-provisioner#328]
Is it possible to configure this provisioner to dynamcially create PVs for an nfs export with existing data.  I've set things up and the storage classes work well but seem to only be able to present to the pods a directory that is generated from within the exported filesystem under `${namespace}-${pvcName}-${pvName}`.  I have some very large exports (multiple TB of data each) that are used by many deployments on our cluster as well was shared to non-containerized applications on other servers.

**Comment by Starttoaster** [comment]
For this, what I've usually done is just `mv` the files from the old location on the NFS server to the directory generated by this provisioner. This provisioner is actually very simple if you read its code, all of that code existing in one fairly short file (not including its dependencies of course.) I find it unlikely that the maintainers here add this feature. Interesting idea though.
