### ISSUE TITLE
Unable to deploy on Rancher v2.5.x

### ISSUE THREAD

**Issue by BenB196** [kubernetes-sigs/nfs-subdir-external-provisioner#33]
Attempted to add this repo as a Chart Repository on Rancher v2.5.x. 

Got the following error:
```
symlink found at path management-state/git-repo/nfs-client/8603be7eb67ce0862b18415007f6eacdd72141d0f92ef0e7bc73bd35f9af9fb7/.cloudbuild.sh 
```

Git Repo URL: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.git
Branch: Master

**Comment by yonatankahana** [comment]
this repository is not helm chart repository.
in fact, no version of this repository has come out yet and there is no official chart release to pull.
keep following.

**Comment by yonatankahana** [comment]
you can now use this repository as helm repository. happy helming :+1:

**Comment by BenB196** [comment]
Yep, able to add the repo as a helm repository now. Thanks for the work on this.
