### ISSUE TITLE
NFS provisioner fails in OpenShift version 4.15

### ISSUE THREAD

**Issue by abhinavk001** [kubernetes-sigs/nfs-subdir-external-provisioner#333]
On deploying NFS storage provisioner in OpenShift 4.15, the pod fails with message: `MountVolume.SetUp failed for volume "<volume-name>" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t`.

### Steps to replicate.
- Create an OpenShift 4.15 instance.
- Setup NFS server on a RHEL 8 host machine.
- Create the roles, role binding, class and deployment in the cluster

**Comment by jagraj** [comment]
@abhinavk001 
Thanks for opening this issue. To isolate this problem, we also tried NFS provisioner on OpenShift 4.14.12 and we don't see this problem and the provisioner works fine. Looks like NFS provisioner is regressed on OpenShift 4.15 version.

**Comment by jagraj** [comment]
We have firewall enabled in our host where NFS server is running. We had to follow these instructions to run the NFS server behind the firewall.

**Configuring an NFSv3 client to run behind a firewall**
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_file_systems/mounting-nfs-shares_managing-file-systems#proc_configuring-an-nfsv3-client-to-run-behind-a-firewall_mounting-nfs-shares

**Configuring an NFSv4 client to run behind a firewall**
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_file_systems/mounting-nfs-shares_managing-file-systems#proc_configuring-an-nfsv4-client-to-run-behind-a-firewall_mounting-nfs-shares
