### ISSUE TITLE
connect to multi-homed nfs server

### ISSUE THREAD

**Issue by DraconPern** [kubernetes-sigs/nfs-subdir-external-provisioner#335]
This is feature request.  For nfs server that are multi-homed e.g. have multiple ip addresses on different network for multi pathing, is there anyway to specify multiple ip address. Thanks!

**Comment by LoneExile** [comment]
I encountered this issue as well. My solution was to create a new namespace and StorageClass with a new `provisioner` name.

I use Kustomize for the creation process. To ensure that everything is set up correctly, run `kubectl apply -k . --dry-run=server`. You should only see `created` and **not** `unchanged` or `changed` in the output.

or you can use Helm [install-multiple-provisioners](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md#install-multiple-provisioners)

After that, run test YAML files. Everything should work. Cheers!
