### ISSUE TITLE
After create provisioner deplopy pod, cloud't create pv to NFS path

### ISSUE THREAD

**Issue by luanshuo** [kubernetes-sigs/nfs-subdir-external-provisioner#339]
In our cluster,we have two nfs server,so we create two provisioner
example: nfs-a, nfs-b
nfs-b was recently created.

after create nfs-two provisioner,we create some new pvc(nfs5、nfs6、nfs7、nfs8),but long time was no success.

We ran the command "kubectl get pvc" to check the status of the PVC.
<img width="1030" alt="image" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/56577113/c5931597-3cd0-4914-bb3d-2a8378490982">

check provisioner log
<img width="1186" alt="image" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/56577113/a30ed78e-1254-4512-97d4-b34706c7a053">

Then, in our tests, creating new files and directories and performing read and write operations successfully.
create new file/dir all action was success, read or write was success too
<img width="1172" alt="image" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/56577113/fb9c1fe2-ac85-4d12-a8e5-c22dc1c5d96c">

<img width="1188" alt="image" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/56577113/23ed57c3-c375-4e13-b6af-7c5800924477">

After restarting the pod, all PVCs were successfully created.
<img width="1201" alt="image" src="https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/assets/56577113/bafaea27-9717-4be5-aa6a-a4aca1acaa3f">

**Comment by benetaptech** [comment]
666
