### ISSUE TITLE
Deploy with Helm on OKD v4.6.0-0.okd-2021-01-17-185703 fails because of kubeVersion restrictions

### ISSUE THREAD

**Issue by titou10titou10** [kubernetes-sigs/nfs-subdir-external-provisioner#38]
Helm install fails in OKD v4.6 because of the k8s version restrictions defined in`Charts.yaml`

    helm install nfs-client-provisioner . -n nfs-client-provisioner --set nfs.server=xxx.xxx.xxx.xxx,nfs.path=/xxxxx,storageClass.defaultClass=true,replicaCount=2
    Error: chart requires kubeVersion: >=1.9.0 <1.20.0 which is incompatible with Kubernetes v1.19.2-1019+3b012051f912a6-dirty

Removingthe line`kubeVersion: ">=1.9.0 <1.20.0"` in`Charts.yaml`make it deploy and work (after given the right permissions to serviceaccount nfs-client-provisioner-nfs-subdir-external-provisioner of course)

    oc version
    Client Version: 4.6.9
    Server Version: 4.6.0-0.okd-2021-01-17-185703
    Kubernetes Version: v1.19.2-1019+3b012051f912a6-dirty

    helm version
    version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

**Comment by yonatankahana** [comment]
it is a bug. i opened PR to fix it: #39 
thank you.

**Comment by yonatankahana** [comment]
the fix is available in the latest version.

/close
