### ISSUE TITLE
nfs version 4 not working

### ISSUE THREAD

**Issue by Kali-lightsaber** [kubernetes-sigs/nfs-subdir-external-provisioner#42]
nfs version 4 not working on any kubernetes installation. Client mounts only version 3 and helm not pass few mount options like nfs version. If i'll set server version only nfsv4 it's also doesn't work.

**Comment by yonatankahana** [comment]
what version you use? mount options was not effective until we merged #28 and no version released with this fix yet.

**Comment by Kali-lightsaber** [comment]
Latest. I'm wrong with fsid and mount path, sorry. It's only not working on OKD 4.5/4.6. Why?
