### ISSUE TITLE
support multiple (many) namespaces

### ISSUE THREAD

**Issue by therc** [kubernetes-sigs/nfs-subdir-external-provisioner#44]
This is a continuation, more or less, of issue 1210 in the old repo.
I even had a PR that implements what is described here:
https://github.com/kubernetes-retired/external-storage/issues/1210#issuecomment-626232371

Basically, if you need to export the same NFS mount to a large number of namespaces, now you would do this:

1. create a PVC for the mount, using whatever NFS provisioner you want
2. run a second NFS provisioner in the new alias mode. *It also needs to mount the PVC from the previous step.*
3. In every namespace that needs it, create a new PVC with the new provisioner. The namespace users don't need to know or care about the details of where the original mount lives, the NFS provisioner forwards those when needed.

Should I revive PR 1318?

**Comment by kmova** [comment]
Hi @therc, please go ahead with reviving the PR.

**Comment by zippyopstraining** [comment]
Hi Mr. Therc, actually let me explain my issue. I have my application which is running in NS1. That NS1 application has pv,pvc .Now i want to use the data  of NS1 application in application of NS2 with new pv, pvc (like clone the NS1's pv). Is there any way?. You said that we can do "https://github.com/kubernetes-retired/external-storage/issues/1210#issuecomment-626232371"  .There you mentioned ,we have to change "allow NFS_SERVER to be set to "auto" (or a new AUTO_NFS_SERVER=true)
allow NFS_PATH to be set to "clone" (or a new CLONE_NFS_PATH=true)" . where do i change this? 
![image](https://user-images.githubusercontent.com/77266301/117930744-00def500-b31c-11eb-9e92-cddedd7c1dd4.png)
