### ISSUE TITLE
arm vm install nfs persistence docker images start failed

### ISSUE THREAD

**Issue by zbh2021** [kubernetes-sigs/nfs-subdir-external-provisioner#45]
1. arm vm install  crate  nfs persistence  but  docker images start failed
![image](https://user-images.githubusercontent.com/64472801/106346127-d084c500-62ef-11eb-9299-b29484e2050a.png)

**Comment by kmova** [comment]
Can you please try with this image: 

`gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:canary`

**Comment by Doriangaensslen** [comment]
image.repository=gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner worked for me

**Comment by yonatankahana** [comment]
> 
> 
> `image.repository=gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner `
> 
> worked for me

since you open this issue we released new provisioner version and new helm chart version. you can use them and they use this latest image by default.
if the problem solved please close the issue :)

**Comment by zbh2021** [comment]
> > `image.repository=gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner `
> > worked for me
> 
> since you open this issue we released new provisioner version and new helm chart version. you can use them and they use this latest image by default without you need to `--set` it.
> if the problem solved please close the issue :)

thank you very much
