### ISSUE TITLE
helm chart does not have recent versions

### ISSUE THREAD

**Issue by darkcloud784** [kubernetes-sigs/nfs-subdir-external-provisioner#50]
The helm chart does not contain recent versions of nfs-subdir-external-provisioner. All are for Kubernetes 1.19.0-0 or below.

**Comment by yonatankahana** [comment]
we are very close to release newer version, please follow #49.

**Comment by yonatankahana** [comment]
check again, the new version released.

**Comment by geoffreyPerrin** [comment]
Hi, I have this error when i'm trying to use the helm chart:
helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
"nfs-subdir-external-provisioner" already exists with the same configuration, skipping
helm install nfs-provisioner-carol-common-services nfs-subdir-external-provisioner/nfs-subdir-external-provisioner     --set nfs.server=test     --set nfs.path=/test
Error: chart requires kubeVersion: >=1.9.0-0 <1.20.0-0 which is incompatible with Kubernetes v1.20.0+k3s2

**Comment by yonatankahana** [comment]
try to `helm repo update` to see if it helps

**Comment by yonatankahana** [comment]
any updates? if solved, please close the issue

**Comment by darkcloud784** [comment]
4.0.0. is currently available but not 4.0.2 which has been the current release for 4 days now.

**Comment by yonatankahana** [comment]
the chart version is 4.0.2 and the application version is 4.0.0.
```console
➜  ~ helm repo list
NAME                           	URL                                                               
nfs-subdir-external-provisioner	https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
➜  ~ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nfs-subdir-external-provisioner" chart repository
Update Complete. ⎈Happy Helming!⎈
➜  ~ helm search repo 
NAME                                              	CHART VERSION	APP VERSION	DESCRIPTION                                       
nfs-subdir-external-provisioner/nfs-subdir-exte...	4.0.2        	4.0.0      	nfs-subdir-external-provisioner is an automatic...
```

**Comment by yonatankahana** [comment]
@darkcloud784 can you please update if the problem solved for you?

**Comment by yonatankahana** [comment]
that's because v4.0.1 isn't officially released yet. we are working on it. follow #76

**Comment by yonatankahana** [comment]
yep

/close

**Comment by mustache1up** [comment]
let's try again?

/close

**Comment by kmova** [comment]
#76 is merged.
