### ISSUE TITLE
arm-image not available

### ISSUE THREAD

**Issue by Ueland** [kubernetes-sigs/nfs-subdir-external-provisioner#57]
I see on some closed issues and PR's that it appears that arm(read:Raspberry Pi's) sould work fine.

I did the helm install on a k3s cluster, when trying to pull the image, k8s logs the following error:

`Failed to pull image "gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0": no match for platform in manifest: not found
`

uname -a
`Linux kube1 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux`

**Comment by yonatankahana** [comment]
can you please confirm if the error gone when using this image: `yonatankahana/nfs-subdir-external-provisioner:armfix`?

```console
--set image.repository=yonatankahana/nfs-subdir-external-provisioner --set image.tag=armfix 
```

**Comment by 1tayH** [comment]
> can you please confirm if the error gone when using this image: `yonatankahana/nfs-subdir-external-provisioner:armfix2`?
> 
> ```
> --set image.repository=yonatankahana/nfs-subdir-external-provisioner --set image.tag=armfix2
> ```

I was having the same issue and this image worked fine for me

**Comment by Ueland** [comment]
@yonatankahana Can confirm that it works, thanks! :)

**Comment by yonatankahana** [comment]
excellent guys, thanks for the confirmation. we will release official image with the fix soon.

**Comment by geoff-coppertop** [comment]
@yonatankahana Can a new release with the arm image be produced?

**Comment by yonatankahana** [comment]
> @yonatankahana Can a new release with the arm image be produced?

cc @kmova

**Comment by geoff-coppertop** [comment]
Bump
