### ISSUE TITLE
[NOOB Question] Cannot see PV

### ISSUE THREAD

**Issue by thisisbenwoo** [kubernetes-sigs/nfs-subdir-external-provisioner#62]
This is brand new to me. From reading the docs, I am deducting that when I deploy this as a Helm chart, that a PV should be created. (Perhaps this is where I'm going wrong). I see if that if I don't use Helm, that in step 4, I need to create my own provisioner. I used a variation of the test-claim.yaml as follows:

`kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi`

But when I do a _kubectl get pvc_ I'm getting the following:
`NAME   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
nfs    Pending                                      managed-nfs-storage   7m53s`

And it never actually binds. What am I doing wrong please? TIA!

**Comment by buccella** [comment]
1.  PVs are created on-demand after a PVC is created
2. The provisioner manages creation of PVs
3. A PV will be bound once a pod is created that uses a PVC

**Comment by yonatankahana** [comment]
buccella's sums it up great
@thisisbenwoo have you succeeded?

**Comment by kmova** [comment]
@thisisbenwoo - you need to run the provisioner prior to creating the PVCs. Either create using the YAML (kubectl apply ) or helm chart.

**Comment by thisisbenwoo** [comment]
Thank you all. It worked!
