### ISSUE TITLE
Proposal: add support to customize the labels and annotations for the resources (deployment, pod, etc)

### ISSUE THREAD

**Issue by quickwind** [kubernetes-sigs/nfs-subdir-external-provisioner#63]
Currently user can't customize the labels or annotations to add additional ones.

**Comment by quickwind** [comment]
@yonatankahana , thanks for the support, seems we still have the deployment template not covered, currently it is only using "nfs-subdir-external-provisioner.selectorLabels" which doesn't include the user defined labels, is there a reason why it is excluded?

**Comment by yonatankahana** [comment]
> @yonatankahana , thanks for the support, seems we still have the deployment template not covered, currently it is only using "nfs-subdir-external-provisioner.selectorLabels" which doesn't include the user defined labels, is there a reason why it is excluded?

there is a [reason](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/72#discussion_r594247776) but when i am thinking about it now - i am not satisfied with the solution. ill fix that.

/reopen

**Comment by quickwind** [comment]
@yonatankahana will this change be merged soon?

**Comment by yonatankahana** [comment]
> @yonatankahana will this change be merged soon?

cc @kmova
