### ISSUE TITLE
Kubectl delete pv and pvc problem

### ISSUE THREAD

**Issue by guidtz** [kubernetes-sigs/nfs-subdir-external-provisioner#64]
Hello,

  I installed and deploy pvc test and pod test but after I want to delete pv and pvc and they are not deleted. They remind in terminating state : 

```
NAME                               STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/test-claim   Terminating   pvc-8b4c4dc6-67f1-4d3a-9cf1-7a7f0b51ba37   1Mi        RWX            nfs-storage    28m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                STORAGECLASS       REASON   AGE
persistentvolume/pvc-8b4c4dc6-67f1-4d3a-9cf1-7a7f0b51ba37   1Mi        RWX            Delete           Terminating   default/test-claim   nfs-storage                 28m
```

I have a debian 10 nfs server for nfs-storage.

Where is the problem ?

Regards

**Comment by thisisbenwoo** [comment]
Has your deployment/pod terminated? If it hasn't the claim will remain in terminating until the deployment/pod is completed. Alternatively, if you want to force kill the PV/PVC, you can add --force to the command. YMMV.

**Comment by guidtz** [comment]
@thisisbenwoo so stange now all is deleted ! I'll go to retest this later ! thanks for you're response

**Comment by yonatankahana** [comment]
once the pvc is bounded, its out of the provisioner responsibilities
could be bug but not here
