### ISSUE TITLE
migrate from nfs-client-provisioner to nfs-subdir-external-provisioner

### ISSUE THREAD

**Issue by harridu** [kubernetes-sigs/nfs-subdir-external-provisioner#73]
What is the migration procedure from the deprecated nfs-client-provisioner to the new nfs-subdir-external-provisioner?

**Comment by harridu** [comment]
Actually it was quite easy: Uninstall the old nfs-client-provisioner and install the new nfs-subdir-external-provisioner using the same command line arguments.

**Comment by tulanian** [comment]
For PVs created with the nfs-client-provisioner, when the PVC is deleted will the backingstore directory be orphaned because the provisioner no longer exists?

**Comment by kmova** [comment]
@tulanian -- as long as the storage class name is the same - it will be deleted.

**Comment by paddy-hack** [comment]
For the record, I didn't feel like uninstalling so I tried an upgrade with
``` console
$ helm upgrade --install --values hdd-cache.yml storage-hdd-cache nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
Error: UPGRADE FAILED: cannot patch "hdd-cache" with kind StorageClass: StorageClass.storage.k8s.io "hdd-cache" is invalid: provisioner: Forbidden: updates to provisioner are forbidden.
```
where the values file looks like
``` yaml
storageClass:
  name: hdd-cache
  defaultClass: true

nfs:
  server: nfs-server.machine.internal
  path: /srv/nfs-exports/cache
```

Since that didn't quite succeed, I deleted the StorageClass and tried again
``` console
$ kubectl delete storageclasses.storage.k8s.io hdd-cache 
storageclass.storage.k8s.io "hdd-cache" deleted
$ helm upgrade --install --values hdd-cache.yml storage-hdd-cache nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
Release "storage-hdd-cache" has been upgraded. Happy Helming!
NAME: storage-hdd-cache
LAST DEPLOYED: Mon Apr 26 11:41:24 2021
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None
```
and confirmed that all PersistentVolumes and PersistentVolumeClaims were still there and functional.

**Comment by nkaplatt** [comment]
Just to chime in, did a very similar process to @paddy-hack and seems to have worked out okay.

**Comment by slaterx** [comment]
For those who landed here looking to do this migration without helm, I just replaced the old image URL with `k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2`.

That worked for both upstream nfs-client-provisioner AND the one available on Quay (quay.io).
