### ISSUE TITLE
Using multiple NFS server

### ISSUE THREAD

**Issue by svasseur** [kubernetes-sigs/nfs-subdir-external-provisioner#78]
i want use 2 NFS server, with helm i launch 
the first nfs-client

`helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \`
` --set nfs.server=172.20.20.93 \`
`--set nfs.path=/nfs`

and another 

`helm install nfsbis-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \`
`    --set nfs.server=172.20.20.39 \`
 `   --set nfs.path=/nfs \`
 `   --set storageClass.name=nfs-clientbis \`
 `   --set storageClass.provisionerName=nfsbis-subdir-external-provisioner`
when create a volume on the second nfs-clientbis in the pod logs i see the volume but it's create in the first nfs-client  

I don't know if it's possible to do that 
thanks

**Comment by yonatankahana** [comment]
sorry but i am not sure that i got what is your question
please show your volumes and pvc's and try to explain a bit more :)

**Comment by svasseur** [comment]
i try to install and use 2 nfs server, but all pvc request go to the first nfs server only

**Comment by yonatankahana** [comment]
attach the yaml of your pvc's

**Comment by svasseur** [comment]
[nfsbis.txt](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/files/6259039/nfsbis.txt)

**Comment by yonatankahana** [comment]
please send yamls of both pvc's and both pv's

**Comment by svasseur** [comment]
[nfs-subdir-external-provisioner.txt](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/files/6259103/nfs-subdir-external-provisioner.txt)
[nfs.txt](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/files/6259104/nfs.txt)
[nfsbis-subdir-external-provisioner-nfs-subdir-external-provisio.txt](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/files/6259105/nfsbis-subdir-external-provisioner-nfs-subdir-external-provisio.txt)
[nfsbis.txt](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/files/6259107/nfsbis.txt)
![image](https://user-images.githubusercontent.com/10127009/113596527-bc847900-963a-11eb-89b8-e0e6c72ba4ed.png)
![image](https://user-images.githubusercontent.com/10127009/113596574-cdcd8580-963a-11eb-8597-5fbcfbc9178f.png)
and everything is create on the first server 
`re7-ubuntu-nfs1:/nfs$ ls *nfs*

hello-nfs-pvc-612f8543-fb5b-4c35-8585-2b1e62b72693:

hello-nfsclientbis-pvc-f7a90ab8-c476-4ae4-bb4f-e105d8160e95:`
