### ISSUE TITLE
Enable using kubeconfig file to connect to apiserver

### ISSUE THREAD

**Issue by onesolpark** [kubernetes-sigs/nfs-subdir-external-provisioner#8]
Currently nfs-provisioner only supports in cluster kubeconfig
```config, err := rest.InClusterConfig()```

Is there a plan to add support for provisioners that are not in cluster and uses kubeconfig file?

**Comment by kmova** [comment]
@onesolpark - does the above PR resolve this issue for you?

**Comment by onesolpark** [comment]
@kmova yes it does I will close this issue thanks :)
