### ISSUE TITLE
Don't use staging registry as stable images

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/nfs-subdir-external-provisioner#86]
Container images in the staging registry are only for dev/CI purposes and automatically get deleted after 30 days.

Official images should be promoted from staging to the release repository when new releases are cut.

/assign @kmova

**Comment by yonatankahana** [comment]
@kmova if there is anything i can do to help, please let me know

**Comment by kmova** [comment]
Thanks, @msau42!

@yonatankahana, could you please raise a PR to promote with the steps outlined here. 
https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#image-promoter

**Comment by yonatankahana** [comment]
follow: https://github.com/kubernetes/k8s.io/pull/1917
