### ISSUE TITLE
Can run 2+ replicas?

### ISSUE THREAD

**Issue by Zhang21** [kubernetes-sigs/nfs-subdir-external-provisioner#88]
default replica: 1
want repicas: 2+
problem: If the k8s node(nfs-subdir-external-provisioner on it) is down，the nfs-provisoner storageclass can't use.

So, can change 1 replica to 2+ replicas to avoid nfs-provisoner temporary unavailable?

**Comment by hzliangbin** [comment]
@Zhang21 hi, maybe there is a issue you can refer to  #19

**Comment by Zhang21** [comment]
2 replicas no error, close issue.

**Comment by circulosmeos** [comment]
Hi @Zhang21 
Could you please elaborate on this?: 
Does #19 resolve your issue? That is, two replicas implies full availavility even if one pod fails, bearing in mind that they are running in leader/wait configuration.

Have you tested speed of down/up cases?
Are the second pod always started on a different node of the cluster?

Greetings!
