### ISSUE TITLE
Is helm chart contains updated image tag

### ISSUE THREAD

**Issue by gvital3230** [kubernetes-sigs/nfs-subdir-external-provisioner#96]
Hi!

Is it possible that helm chart contains image tag, that does not correspond repo tag?

Because I see [4.0.2](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/ae50b6da6c35d7c90187527cae96d780f55dbbec/charts/nfs-subdir-external-provisioner/values.yaml#L6) in values.yaml and this feature is not work for me

https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/commit/b8e203661b0b2d3be35342be8869de2125782ebc

But when I build and push it from fork to my own repository, it works fine

**Comment by yonatankahana** [comment]
You need to differentiate between versions of the helm chart and versions of the provisioner itself.

provisioner [v4.0.2](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/releases/tag/v4.0.2) released in 27 March and the commit you showed merged on 31 March and not yet released as official version.

you can see all the provisioner chagnes in the [CHANGELOG](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/CHANGELOG.md).

**Comment by gvital3230** [comment]
Oh, I see. Thanks!
