### ISSUE TITLE
how to change the old nfs provider to the new one on a cluster with allready mounted NFS PVCs?

### ISSUE THREAD

**Issue by betonmoewe** [kubernetes-sigs/nfs-subdir-external-provisioner#99]
Hi,

is there a way to replace the old provider with the new one for a running cluster with already existing NFS PVCs? Or simply delete helm chart and roll out the new one (the names remain the same of course) ?

_Originally posted by @petermicuch in https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25#issuecomment-818762464_

**Comment by petermicuch** [comment]
You can just use new provisioner without any need to worry about existing volumes. Provisioner just provisions volumes for you. Once they are created, they would work even if you would delete nfs provisioner.

**Comment by betonmoewe** [comment]
Hi

thanks for your answer ... but ... where are the information stored how to deal with deleted pvc s  like  the onDelete  or archiveOnDelete option? If I delete the old one and install the new (with the same StarageClass Name etc) the old pvcs are then still treated normally as desired?
It's a semeproductive Cluster and I don't want to loose any pvc

Best regards

Frank

**Comment by petermicuch** [comment]
My assumption is, that as long as you keep the same provisioner name reference in the SC, it also handles events for PVCs that were created by the old version of provisioner (so make sure env variable `PROVISIONER_NAME` in old and new provisioner version are identical). There is no other link between PVC->SC->provisioner other than then its names and annotation in PVC `volume.beta.kubernetes.io/storage-provisioner` that refers to provisioner name. But try it out with some dummy volume if you want to be sure.
